// GENERATED by tools/gen_scad_frame.py - DO NOT EDIT.
// Every value comes from tools/design.py, which is the single source of truth for the
// airframe. Edit it there and regenerate, or the model and the checks drift apart again.
//
// frame : [D] github.com/tbs-trappy/source_one So1-V6-7inDC-2025-JUL-07.dxf, stack patterns parsed directly 2026-09-02; [L] hobbyrc.co.uk for standoffs 30/22 mm, plates and 143.5 g; [A] plate outline 200x230 mm - overall footprint only, not load-bearing on any check
// motor : [D] 41 g, M3 19x19, M5 prop adapter thread, 12N14P (BrotherHobby Avenger product data); [A] 1250 g thrust; [D] 28 mm body from the 2806.5 stator designation, [A] 15 mm bell height
// plates: [D] tools/parse_frame_dxf.py -> cad/frame-dxf.json from So1-V6-7inDC-2025-JUL-07.dxf (sha 398556cd); re-derivable, not a one-off flatten
// batt  : [L] retailer listing
// prop  : [D] Gemfan Flash 7040-3 published spec: 5 mm centre hole, 178.43 mm disc, 7.9 g, PC. Bore matches the [D] M5 motor shaft. A different brand of 7040 may differ in mass; the 5 mm bore is universal for 7in

wheelbase      = 320.0;
frame_size_x   = 200.0;
frame_size_y   = 230.0;
inner_h        = 22.0;
bottom_plate_t = 2.5;
medium_plate_t = 2.0;
upper_plate_t  = 2.0;
arm_t          = 6.0;
cam_plate_t    = 2.0;

motor_dia      = 28.0;
motor_h        = 15.0;
prop_dia       = 178.4;

batt_l = 138; batt_w = 47; batt_h = 48;

// ---- PLATE OUTLINES, PARSED FROM THE MANUFACTURER DXF ---------------------
// drone.scad drew ALL THREE plates as one 50 mm square, from a variable whose own
// comment called it a placeholder ("must be >= fc_w = 46.10"). Every frame-vs-anything
// clearance check_cad_fit.py reported was therefore measured against an airframe that
// does not exist - and the error was not small or in the safe direction: the real top
// plate is 160.26 mm long, more than three times the placeholder, reaching 80 mm out
// under a prop disc of 89.2 mm radius.
//
// These are [M], flattened from So1-V6-7inDC-2025-JUL-07.dxf. The three plates are
// genuinely different shapes and the model now says so.
fc_plate_w     = 48.5;    // the mid plate: carries the 30.5 mm stack pattern
fc_plate_l     = 106.59;
top_plate_w    = 42.5;    // carries the battery - and the battery OVERHANGS it
top_plate_l    = 160.26;
bot_plate_w    = 48.5;
bot_plate_l    = 107.62;
arm_plate_w    = 31.08;   // widest point of an arm, at the motor end
arm_plate_l    = 185.21;
batt_overhang  = 2.25;   // per side, battery vs top plate

// ---- STACK HEIGHTS, MEASURED FROM THE BOARD -------------------------------
// NOT hardcoded. drone.scad carried fc_bot_parts = 2.50 while design.stack_heights()
// measured 3.00 on the real board (L5, the 10 uH inductor) - so the model showed
// 0.5 mm MORE clearance to the ESC than exists. Three copies of this number have
// already disagreed once in this project (2.5 / 2.3 / 3.0); this is the fourth, and
// it is now generated so it cannot be the fifth.
fc_l           = 45.10;   // Edge.Cuts bbox - conservative
fc_w           = 46.10;
fc_l_fab       = 45.00;   // centreline: what JLC routes to
fc_w_fab       = 46.00;
fc_pcb         = 1.60;
fc_top_parts   = 4.4;          // tallest: J3
fc_bot_parts   = 2.9;          // tallest: J11

esc_l          = 45.6;
esc_w          = 44.0;
esc_pcb        = 1.6;
esc_parts      = 6.2;

skid_t          = 3.5;
cam_drop        = 40.0;

// Nose recording camera - XIAO ESP32S3 Sense. rec_cam_y is how far forward it sits;
// the prop discs clear the nose by 24-71 mm anywhere along it, so this is free choice.
rec_cam_l       = 21.0;
rec_cam_w       = 17.5;
rec_cam_h       = 13.0;
rec_cam_y       = 78.0;

// Belly sensor - the downward rangefinder now, a flow+range module later. Mounts UNDER
// the bottom plate because that is the only place anything can see the ground.
belly_h         = 12.0;
belly_l         = 36.0;
belly_w         = 16.0;

// 360 lidar (LDROBOT LD06), belly-mounted upside-down - PRX1_ORIENT 1. Dimensions are
// [D] datasheet, not guessed, and they are the reason SKID['drop'] went 25 -> 40 mm
// (35 was tried first and rejected - 5.20 mm clearance; see the SKID note in design.py):
// at 25 mm the belly had 28.5 mm of depth against a 33.30 mm lidar.
lidar_l         = 38.59;
lidar_w         = 38.59;
lidar_h         = 33.3;
lidar_y         = -22.0;   // aft of the downward rangefinder at y=+18
skid_hole_pitch = 19.0;
gap             = 3.0;    // compressed grommet - [A], re-measure on assembly
grommet_dia     = 6.0;
hole_pitch      = 30.5;
hole_dia        = 4.0;
plate_hole_dia  = 3.2;   // M3 close clearance, > screw_dia
screw_dia       = 3.0;     // M3

// TOP PLATE HEIGHT IS THE KIT'S GEOMETRY (design.TOP_PLATE_MOUNT), not a purchase.
// The DXF settles it: 22 mm standoffs stand on the MID plate at the front posts, 30 mm
// on the BOTTOM plate at the rear posts, and one flat top plate needs 22 + 8 = 30.
// standoff_len is the top plate's underside above z = 0 (bottom of the bottom plate).
standoff_len    = 32.5;   // = bottom_t + 30 = mid plate top + 22
standoff_front  = 22.0;
standoff_rear   = 30.0;
post_od         = 5.0;
front_posts     = [[-14.6, -27.88], [14.6, -27.88], [-14.6, -52.88], [14.6, -52.88]];   // on the mid plate, rel. stack centre
rear_posts      = [[-14.6, 27.88], [14.6, 27.88], [-11.0, 80.75], [11.0, 80.75]];   // on the bottom plate
plate_y_fc      = -29.16;    // plate centres rel. the stack centre, +y aft
plate_y_bottom  = 31.09;
plate_y_top     = 4.78;
standoff_need   = 30.2;   // stack top above z = 0
standoff_slack  = 2.3;  // headroom under the top plate
cam_mod_t       = 12.0;
cam_mod_w       = 30.0;
pi_l            = 65.0;
pi_w            = 30.0;
pi_t            = 1.2;
