// GENERATED by tools/gen_scad_mounts.py - DO NOT EDIT.
// Every value comes from tools/design.py (MOUNTS, MOUNTED, INSERTS). Edit it there and
// regenerate, or the model, the CAD fit check and tools/fasteners.py drift apart.
//
// Axes as drone.scad: x to starboard, y AFT (the nose is -y), z up from the bottom plate's
// underside, (0, 0) the stack centre. Each mount is drawn where it sits on the aircraft;
// print_*() lays it on the bed.
//
// Heat-set inserts are bores [diameter, depth, boss diameter]: [L] CNC Kitchen heat-set insert range as listed by kb-3d.com: M2 x 3.0 in a 3.2 mm bore, M2.5 x 4.0 in 4.0 mm; [A] the outside diameters and the 1.6 mm wall - check against the pack

ins_m2  = [3.2, 4.0, 6.8];
ins_m25 = [4.0, 5.0, 7.8];

module bore(i, up = true) {        // an insert bore, from the face it is pressed into
    translate([0, 0, up ? -i[1] : 0]) cylinder(d = i[0], h = i[1] + 0.01, $fn = 24);
}
module hole(d, h) { translate([0, 0, -0.5]) cylinder(d = d, h = h + 1, $fn = 24); }
module box(x0, x1, y0, y1, z0, z1) { translate([x0, y0, z0]) cube([x1 - x0, y1 - y0, z1 - z0]); }

// ---- antenna tower: the Iridium helix on its seat, the GPS pod and bias tee on the arm --
// Bolts through the top plate's two rear posts, the only top-plate holes the battery
// leaves free, into the kit's 30 mm standoffs; the seat has holes to reach those screws.
tower_foot_z  = 34.5;
tower_post_y  = 80.75;
seat_z        = 64.0;            // the helix's base
helix_y       = 84.0;
gps_y         = 164.0;
gps_z         = 93.10;      // module underside; its top is 105.50
pod_top_z     = 101.10;
gps_lid_t     = 2.0;
gps_screw_x   = 15.30;
bias_y        = 126.0;
module antenna_tower() {
    fx = 18.0; fy = 12.0; cx = 7.5; cy = 8.0;
    cy0 = 84.0; w = 2.4; st = 4.0; at = 4.0;
    ax = 22.0; wb = 1.5; web0 = helix_y + 10.0 + 3;
    color("#d9822b") difference() {
        union() {
            box(-fx, fx, tower_post_y - fy, tower_post_y + fy, tower_foot_z, tower_foot_z + 4.0);
            box(-cx, cx, cy0 - cy, cy0 + cy, tower_foot_z, seat_z - st);
            box(-20.0, 20.0, 68.0, 104.0, seat_z - st, seat_z);
            box(-ax, ax, 104.0 - 1, 178.0, seat_z - at, seat_z);
            box(-wb, wb, web0, 178.0, seat_z - at - 16.0, seat_z - at);
            // under the arm, bosses for the strap's inserts
            for (s = [-1, 1]) translate([10.0 / 2 + 3, bias_y + s * 19.5, seat_z - at - 3])
                cylinder(d = ins_m2[2], h = 3.01);
        }
        // the foot screws, and holes in the seat to reach them
        for (x = [-11.0, 11.0]) translate([x, tower_post_y, tower_foot_z]) {
            hole(3.4, 4.0);
            translate([0, 0, seat_z - st - tower_foot_z]) hole(7, st);
        }
        // the column is a duct for the helix's SMA and cable, out through its side
        box(-cx + w, cx - w, cy0 - cy + w, cy0 + cy - w, tower_foot_z + 4.0, seat_z + 1);
        box(cx - w - 1, cx + 1, cy0 - 4, cy0 + 4, seat_z - st - 12, seat_z - st);
        for (h = [[0.0, 74.0], [0.0, 94.0]]) translate([h[0], h[1], seat_z - st]) hole(2.9, st);
        // the GPS pod's screws come up through the arm; the strap's go down into it
        for (s = [-1, 1]) translate([s * gps_screw_x, gps_y, seat_z - at]) hole(2.4, at);
        for (s = [-1, 1]) translate([10.0 / 2 + 3, bias_y + s * 19.5, seat_z]) bore(ins_m2);
    }
}
module gps_pod() {
    px = 18.700000000000003; py = 14.0; g = 10.3; w = 2.0;
    h = pod_top_z - seat_z; floor = gps_z - seat_z;
    color("#e0a050") translate([0, gps_y, seat_z]) difference() {
        box(-px, px, -py, py, 0, h);
        difference() {                                       // hollow, but for the bosses
            box(-px + w, px - w, -py + w, py - w, w, floor - w);
            for (s = [-1, 1]) translate([s * gps_screw_x, 0, 0]) cylinder(d = ins_m2[2], h = h);
        }
        box(-g, g, -g, g, floor, h + 1);                      // the GPS pocket
        box(-4, 4, -py - 1, 0, floor, h + 1);                 // its lead, toward the helix
        for (s = [-1, 1]) translate([s * gps_screw_x, 0, 0]) { bore(ins_m2, false); translate([0, 0, h]) bore(ins_m2); }
    }
}
module gps_lid() {
    px = 18.700000000000003; py = 14.0; g = 10.3;
    color("#e0a050") translate([0, gps_y, pod_top_z]) difference() {
        box(-px, px, -py, py, 0, 4.4 + gps_lid_t);
        box(-g, g, -g, g, -1, 4.4);                  // over the module's shoulders
        box(-8, 8, -8, 8, 0, 4.4 + gps_lid_t + 1);   // the ceramic patch sees sky
        for (s = [-1, 1]) translate([s * gps_screw_x, 0, 0]) {
            hole(2.4, 4.4 + gps_lid_t);
            translate([0, 0, 4.4 + gps_lid_t - 2.0]) cylinder(d = 4.2, h = 2.0 + 1, $fn = 24);
        }
    }
}
module bias_strap() {                // a bridge over the bias tee, two screws into the arm
    x0 = 10.0 / 2 + 3 - 10.0 / 2; x1 = x0 + 10.0; t = 3.0;
    hw = 16.5; top = seat_z + 12.0 + 0.3;
    color("#e0a050") difference() {
        union() {
            for (s = [-1, 1]) {
                translate([x0, s > 0 ? bias_y + hw : bias_y - hw - 5.5, seat_z]) cube([x1 - x0, 5.5, t]);
                translate([x0, s > 0 ? bias_y + hw : bias_y - hw - 2, seat_z]) cube([x1 - x0, 2, top + t - seat_z]);
            }
            box(x0, x1, bias_y - hw - 2, bias_y + hw + 2, top, top + t);
        }
        for (s = [-1, 1]) translate([10.0 / 2 + 3, bias_y + s * 19.5, seat_z]) hole(2.4, t);
    }
}
module gps() {
    translate([0, gps_y, gps_z]) {
        color("#3050a0") box(-10.0, 10.0, -10.0, 10.0, 0, 8.4);
        color("#c8b070") box(-7.5, 7.5, -7.5, 7.5, 8.4, 12.4);
    }
}
module iridium_antenna() {          // Tallysman HC610: radome over the helix, SMA below
    translate([0, helix_y, seat_z]) {
        color("#2b2b2b") cylinder(d1 = 33.3, d2 = 28.5, h = 54.2, $fn = 48);
        color("#c8b070") translate([0, 0, -10]) cylinder(d = 8, h = 10, $fn = 24);
    }
}
module bias_tee() {
    translate([0, bias_y, seat_z]) {
        color("#9aa0a6") box(-21.0, 21.0, -16.0, 16.0, 0, 12.0);
        color("#c8b070") for (s = [-1, 1]) translate([s * 21.0, 0, 6.0])
            rotate([0, s * 90, 0]) cylinder(d = 6.5, h = 8, $fn = 24);
    }
}

// ---- nose mount: XIAO camera, RP3 receiver, both ELRS antennas ---------------------------
// Clamped under the mid plate by the two forward front-post screws, in the gap the arms
// leave there. Everything hangs below the plate. Ahead of the carbon, and the length of
// the aircraft from the Iridium antenna.
nose_z   = 8.5;                 // the mid plate's underside
cam_y    = -97.0;
rx_y     = -71.0;
cam_x    = 11.05;      // cradle half-width
cam_d    = 8.8;      // cradle half-depth
cam_boss = cam_x + ins_m2[2] / 2 - 1;
cam_bot  = nose_z - 3.0 - 21.0 - 0.3 - 2.0;     // 0.3 mm headroom
rx_w     = 8.3;
rx_l     = 12.799999999999999;
rx_bot   = nose_z - 3.0 - 4.4;
rx_boss  = rx_w + ins_m2[2] / 2 - 1;
module nose_mount() {
    t = 3.0; hx = 24.0; pz = nose_z - t; cw = 2.0;
    color("#d9822b") difference() {
        union() {
            box(-hx, hx, -106.0, -47.0, pz, nose_z);
            // camera cradle, the XIAO slides in from below; with its lid's bosses
            box(-cam_x, cam_x, cam_y - cam_d, cam_y + cam_d, cam_bot, pz);
            for (s = [-1, 1]) translate([s * cam_boss, cam_y, cam_bot]) cylinder(d = ins_m2[2], h = pz - cam_bot);
            // receiver pocket, with its cover's bosses
            box(-rx_w, rx_w, rx_y - rx_l, rx_y + rx_l, rx_bot, pz);
            for (s = [-1, 1]) translate([s * rx_boss, rx_y, rx_bot]) cylinder(d = ins_m2[2], h = pz - rx_bot);
            // antenna holders: one vertical (up through the plate), one pointing forward
            translate([19.0, -90.0, pz - 12]) cylinder(d = 8, h = 12);
            box(-24.0, -14.0, -106.0, -101.0, -4.0, pz);
        }
        for (p = [[-14.6, -52.88], [14.6, -52.88]]) translate([p[0], p[1], pz]) hole(3.4, t);
        box(-cam_x + cw, cam_x - cw, cam_y - cam_d + cw, cam_y + cam_d - cw, cam_bot - 1, pz - 0.01);
        translate([0, cam_y - cam_d - 1, cam_bot + cw + 21.0 - 7]) rotate([-90, 0, 0]) cylinder(d = 10, h = cw + 2);
        for (s = [-1, 1]) translate([s * cam_boss, cam_y, cam_bot]) bore(ins_m2, false);
        box(-rx_w + 1.6, rx_w - 1.6, rx_y - rx_l + 1.6, rx_y + rx_l - 1.6, rx_bot - 1, pz - 0.01);
        box(-3, 3, rx_y + rx_l - 1.6 - 0.01, rx_y + rx_l + 0.01, rx_bot + 1, pz - 0.01);   // wires out
        for (s = [-1, 1]) translate([s * rx_boss, rx_y, rx_bot]) bore(ins_m2, false);
        translate([19.0, -90.0, pz - 12]) hole(3.4, 12 + t);
        translate([-19.0, -106.0 - 0.5, 0.0]) rotate([-90, 0, 0]) cylinder(d = 3.4, h = 6, $fn = 24);
    }
}
module xiao_lid() {
    color("#e0a050") translate([0, cam_y, cam_bot - 2.0]) difference() {
        box(-cam_boss - ins_m2[2] / 2, cam_boss + ins_m2[2] / 2, -cam_d, cam_d, 0, 2.0);
        for (s = [-1, 1]) translate([s * cam_boss, 0, 0]) hole(2.4, 2.0);
    }
}
module rx_cover() {
    color("#e0a050") translate([0, rx_y, rx_bot - 1.5]) difference() {
        box(-rx_boss - ins_m2[2] / 2, rx_boss + ins_m2[2] / 2, -rx_l, rx_l, 0, 1.5);
        for (s = [-1, 1]) translate([s * rx_boss, 0, 0]) hole(2.4, 1.5);
    }
}
module rec_cam() {                  // XIAO ESP32S3 Sense, standing in its cradle, lens forward
    translate([0, cam_y, cam_bot + 2.0]) {
        color("#23272e") box(-8.75, 8.75, -6.5, 6.5, 0, 21.0);
        color("#0d0f11") translate([0, -6.5, 14.0]) rotate([90, 0, 0]) cylinder(d = 8.0, h = 3);
    }
}
module rx() {
    translate([0, rx_y, rx_bot + 0.2]) color("#202020")
        box(-6.5, 6.5, -11.0, 11.0, 0, 4.0);
}
module elrs_antennas() {
    color("#101010") {
        translate([19.0, -90.0, nose_z - 3.0 - 10]) cylinder(d = 3.0, h = 65.0, $fn = 16);
        translate([-19.0, -106.0 + 4, 0.0]) rotate([90, 0, 0]) cylinder(d = 3.0, h = 65.0, $fn = 16);
    }
}

// ---- lidar bracket: the LD06, upside down under the bottom plate ------------------------
// Hangs from the two forward rear-post screws (into the 30 mm standoffs) and the front
// pair of the 20x20 M2 holes; the heads sit in counterbores because the lidar covers them.
lidar_bracket_t = 5.0;
lidar_y         = 24.0;
module lidar_bracket() {
    t = 5.0; cb = 3.2;
    color("#d9822b") difference() {
        box(-22.0, 22.0, 3.0, 48.0, -t, 0);
        for (p = [[-14.6, 27.88], [14.6, 27.88]]) translate([p[0], p[1], -t]) { hole(3.4, t); translate([0, 0, -1]) cylinder(d = 6.0, h = cb + 1, $fn = 24); }
        for (p = [[-10.0, 43.5], [10.0, 43.5]]) translate([p[0], p[1], -t]) { hole(2.4, t); translate([0, 0, -1]) cylinder(d = 4.2, h = cb + 1, $fn = 24); }
        // the LD06's two diagonal M2.5 holes, screwed from the lidar's side
        for (s = [-1, 1]) translate([s * 14.1, lidar_y - s * 14.1, -t]) bore(ins_m25, false);
    }
}
module lidar360() {
    translate([0, lidar_y, -lidar_bracket_t - 33.3]) color("#3b4048")
        linear_extrude(33.3) offset(r = 2) square([34.59, 34.59], center = true);
}

// ---- downward rangefinder cradle: the TFS20-L, under the bottom plate -------------------
// Two M2 through the lid, the cradle and the plate, nuts on top: the sensor has no holes,
// so the lid pins it in its pocket.
range_y      = 63.5;
range_body_h = 9.67;
module range_cradle() {
    hx = 14.0; hy = 13.0; px = 7.7; py = 10.7;
    color("#d9822b") translate([0, range_y, -range_body_h]) difference() {
        box(-hx, hx, -hy, hy, 0, range_body_h);
        box(-px, px, -py, py, -1, range_body_h - 1.5);
        box(-2.5, 2.5, py - 0.01, hy + 0.01, 0, 3);             // the lead's exit
        for (h = [[-10.0, 63.5], [10.0, 63.5]]) translate([h[0], h[1] - range_y, 0]) hole(2.4, range_body_h);
    }
}
module range_lid() {
    hx = 14.0; hy = 13.0;
    color("#e0a050") translate([0, range_y, -range_body_h - 1.5]) difference() {
        box(-hx, hx, -hy, hy, 0, 1.5);
        box(-5, 5, -8, 8, -1, 1.5 + 1);                 // the optics' window
        for (h = [[-10.0, 63.5], [10.0, 63.5]]) translate([h[0], h[1] - range_y, 0]) hole(2.4, 1.5);
    }
}
module belly_sensor() {
    translate([0, range_y, -1.5 - 7.87]) color("#2a2f36")
        box(-7.5, 7.5, -10.5, 10.5, 0, 7.87);
}

module mounts() {
    antenna_tower(); gps_pod(); gps_lid(); bias_strap(); nose_mount(); xiao_lid(); rx_cover();
    lidar_bracket();
    range_cradle(); range_lid();
}
module mounted_parts() {
    gps(); iridium_antenna(); bias_tee(); rx(); elrs_antennas();
}

// ---- laid out for printing: each part on the bed, in the orientation it prints ---------
module print_antenna_tower() { translate([0, 0, seat_z]) rotate([180, 0, 0]) antenna_tower(); }
module print_gps_pod()       { translate([0, 0, -seat_z]) gps_pod(); }
module print_gps_lid()       { translate([0, 0, pod_top_z + 6.4]) rotate([180, 0, 0]) gps_lid(); }
module print_bias_strap()    { translate([0, 0, seat_z + 15.3]) rotate([180, 0, 0]) bias_strap(); }
module print_nose_mount()    { translate([0, 0, nose_z]) rotate([180, 0, 0]) nose_mount(); }
module print_xiao_lid()      { translate([0, 0, -(cam_bot - 2.0)]) xiao_lid(); }
module print_rx_cover()      { translate([0, 0, -(rx_bot - 1.5)]) rx_cover(); }
module print_lidar_bracket() { translate([0, 0, lidar_bracket_t]) lidar_bracket(); }
module print_range_cradle()  { rotate([180, 0, 0]) range_cradle(); }
module print_range_lid()     { translate([0, 0, range_body_h + 1.5]) range_lid(); }
