// GENERATED by tools/gen_scad_plugs.py - DO NOT EDIT.
// The plugged-in assembly (Stage 5): each edge connector's mated plug envelope,
// sized from the footprint's courtyard mouth x design.MATING_CLEARANCE and
// pointing along design.MATING_FACE. Regenerate rather than edit.
//
// INCLUDE this file from drone.scad after fc_z is defined: the plug z needs the
// board's own stack position, which drone.scad owns.

plug_h = 6.0;   // [A] how far a mated plug stands off the board

// One mated plug: a box from the connector's mouth, outward along (ux, uy).
module plug_box(x, y, ux, uy, w, depth, z0, h) {
    translate([x, y, z0])
        rotate([0, 0, atan2(uy, ux)])
            translate([0, -w / 2, 0]) cube([depth, w, h]);
}

module plug_J1() {   // 9.0 mm clearance, 9.00 mm mouth
    plug_box(23.75, -6.00, 1.0000, -0.0000, 9.00, 9.00, fc_z + fc_pcb, plug_h);
}
module plug_J2() {   // 6.0 mm clearance, 12.90 mm mouth
    plug_box(-22.70, 5.40, -1.0000, -0.0000, 12.90, 6.00, fc_z + fc_pcb, plug_h);
}
module plug_J3() {   // 6.0 mm clearance, 10.40 mm mouth
    plug_box(0.00, 23.55, 0.0000, 1.0000, 10.40, 6.00, fc_z + fc_pcb, plug_h);
}
module plug_J5() {   // 6.0 mm clearance, 7.90 mm mouth
    plug_box(-5.60, -23.15, 0.0000, -1.0000, 7.90, 6.00, fc_z - plug_h, plug_h);
}
module plug_J6() {   // 6.0 mm clearance, 7.90 mm mouth
    plug_box(5.60, 23.15, 0.0000, 1.0000, 7.90, 6.00, fc_z - plug_h, plug_h);
}
module plug_J8() {   // 14.0 mm clearance, 15.00 mm mouth
    plug_box(-24.25, -0.50, -1.0000, -0.0000, 15.00, 14.00, fc_z - plug_h, plug_h);
}
module plug_J9() {   // 6.0 mm clearance, 7.90 mm mouth
    plug_box(-5.60, 23.15, 0.0000, 1.0000, 7.90, 6.00, fc_z - plug_h, plug_h);
}
module plug_J11() {   // 6.0 mm clearance, 7.90 mm mouth
    plug_box(5.60, -23.15, 0.0000, -1.0000, 7.90, 6.00, fc_z - plug_h, plug_h);
}
module plug_J12() {   // 6.0 mm clearance, 5.11 mm mouth
    plug_box(20.50, 25.90, 0.0000, 1.0000, 5.11, 6.00, fc_z + fc_pcb, plug_h);
}
module plug_J14() {   // 6.0 mm clearance, 10.40 mm mouth
    plug_box(23.20, 6.70, 1.0000, -0.0000, 10.40, 6.00, fc_z - plug_h, plug_h);
}
module plug_J17() {   // 17.0 mm clearance, 8.00 mm mouth
    plug_box(-4.75, -23.60, 0.0000, -1.0000, 8.00, 17.00, fc_z + fc_pcb, plug_h);
}
module plug_J21() {   // 6.0 mm clearance, 10.40 mm mouth
    plug_box(23.20, 6.70, 1.0000, -0.0000, 10.40, 6.00, fc_z + fc_pcb, plug_h);
}
module plug_J22() {   // 6.0 mm clearance, 6.65 mm mouth
    plug_box(-22.35, -7.30, -1.0000, -0.0000, 6.65, 6.00, fc_z + fc_pcb, plug_h);
}
module plug_J23() {   // 17.0 mm clearance, 8.00 mm mouth
    plug_box(4.75, -23.60, 0.0000, -1.0000, 8.00, 17.00, fc_z + fc_pcb, plug_h);
}

module plugs() {
    plug_J1();
    plug_J2();
    plug_J3();
    plug_J5();
    plug_J6();
    plug_J8();
    plug_J9();
    plug_J11();
    plug_J12();
    plug_J14();
    plug_J17();
    plug_J21();
    plug_J22();
    plug_J23();
}
