#!/usr/bin/env python3
"""Regenerate the tables in sitl/README.md and docs/HARDWARE.md from the code."""
import argparse
import ast
import subprocess
import sys
from pathlib import Path


REPO = Path(__file__).resolve().parent.parent
SPATIAL_BEGIN = "<!-- BEGIN GENERATED SPATIAL -->"
SPATIAL_END = "<!-- END GENERATED SPATIAL -->"
STACK_BEGIN = "<!-- BEGIN GENERATED STACK -->"
STACK_END = "<!-- END GENERATED STACK -->"
SCEN_BEGIN = "<!-- BEGIN GENERATED SCENARIOS -->"
SCEN_END = "<!-- END GENERATED SCENARIOS -->"
FRAME_BEGIN = "<!-- BEGIN GENERATED FRAME -->"
FRAME_END = "<!-- END GENERATED FRAME -->"
FAST_BEGIN = "<!-- BEGIN GENERATED FASTENERS -->"
FAST_END = "<!-- END GENERATED FASTENERS -->"
MODULE_BEGIN = "<!-- BEGIN GENERATED MODULES -->"
MODULE_END = "<!-- END GENERATED MODULES -->"
ORDER_BEGIN = "<!-- BEGIN GENERATED ORDER -->"
ORDER_END = "<!-- END GENERATED ORDER -->"
TEX_ORDER_BEGIN = "% BEGIN GENERATED ORDER"
TEX_ORDER_END = "% END GENERATED ORDER"


def load_scenarios():
    """Read the scenarios dict without importing scenarios.py."""
    src = (REPO / "sitl" / "scenarios.py").read_text()
    for node in ast.parse(src).body:
        if (isinstance(node, ast.Assign) and len(node.targets) == 1
                and getattr(node.targets[0], "id", None) == "SCENARIOS"):
            return eval(compile(ast.Expression(node.value), "<scenarios>", "eval"),
                        {"__builtins__": {"dict": dict}}, {})
    raise SystemExit("FAIL: no SCENARIOS assignment in sitl/scenarios.py")


def kind(v):
    if v.get("expect_arm_failure"):
        return "must FAIL to arm"
    if v.get("dr_scenario"):
        return "pass/fail on applet mode transitions"
    if v.get("expect_mode"):
        return f"pass/fail: aircraft in {v['expect_mode']}"
    if v.get("watch_ekf"):
        return "pass/fail: failsafe must annunciate without acting"
    if v.get("expect_error_near"):
        return "canary - must report the injected offset"
    if v.get("harness_defect"):
        return "known harness defect, recorded not asserted"
    if v.get("expect_blocked_within") is not None or v.get("expect_ceiling") is not None:
        return "pass/fail"
    if v.get("informational"):
        return "informational - no pass/fail"
    if v.get("max_p95") is not None:
        return f"pass/fail, p95 <= {v['max_p95']:g} m"
    return "informational - no pass/fail"


def table(scen):
    rows = ["| Name | What it does | How it is judged |", "|---|---|---|"]
    for name, v in scen.items():
        first = v["why"].split(".")[0].strip().replace("|", "/")
        rows.append(f"| `{name}` | {first} | {kind(v)} |")
    n_info = sum(1 for v in scen.values() if kind(v).startswith("informational"))
    rows += [
        "",
        f"{len(scen)} scenarios; {n_info} are informational by design and "
        f"{len(scen) - n_info} can fail. `flow_only`, `extnav_1hz` and `soop_raw_1hz` "
        "are expected to look bad - a suite where everything passes by construction "
        "measures nothing.",
        "",
        "`./sitl/run_scenarios.sh --list` prints the full rationale for each. "
        "This table is generated by `tools/gen_scenario_table.py`; do not edit it here.",
    ]
    return "\n".join(rows)


def load_frame():
    """design.FRAME, read the same way and for the same reason as the scenarios."""
    src = (REPO / "tools" / "design.py").read_text()
    for node in ast.parse(src).body:
        if (isinstance(node, ast.Assign) and len(node.targets) == 1
                and getattr(node.targets[0], "id", None) == "FRAME"):
            return eval(compile(ast.Expression(node.value), "<design>", "eval"),
                        {"__builtins__": {"dict": dict}}, {})
    raise SystemExit("FAIL: no FRAME assignment in tools/design.py")


F_CAD_W = 1.70
F_CAD_L = 1.04


def npairs():
    """Ask check_cad_fit how many pairs it tests - do not restate the number."""
    sys.path.insert(0, str(REPO / "tools"))
    import check_cad_fit
    return len(check_cad_fit.PAIRS)


def load_standoff():
    """design.required_standoff() needs the real board, so this one does import."""
    sys.path.insert(0, str(REPO / "tools"))
    import design, pcbnew
    return design.required_standoff(pcbnew.LoadBoard(
        str(REPO / "NAVCORE-SoOP.kicad_pcb")))


def spatial_table():
    """What the 3D assembly actually computes, so the record cannot drift from it."""
    sys.path.insert(0, str(REPO / "tools"))
    import design, math
    s = load_standoff()
    F, P, C, S, B = design.FRAME, design.PROP, design.CAMERA, design.SKID, design.BATT
    motor_off = F["wb"] / 2 / math.sqrt(2)
    prop_gap = motor_off * 2 - P["dia_mm"]
    cam_margin = S["drop"] + S["t"] - C["mod_t"] - C["lens_len"]
    rows = [
        ("stack height", f"**{s['below']+s['stack']:.1f} mm** "
         f"({s['below']:.1f} frame + {s['stack']:.1f} stack)",
         f"under the top plate at **{s['top_plate_z']:.1f} mm** (the kit's "
         f"{s['buy']:.0f} mm front standoffs on the mid plate + {F['arm_t']+F['medium_t']:.0f} "
         f"mm of arms and plate); nothing to buy"),
        ("clearance above the FC", f"{s['slack']:.1f} mm",
         f"to the top plate, tallest part `{s['topref']}`"),
        ("FC/ESC mounting", f"{design.MOUNTING['pitch']} x {design.MOUNTING['pitch']} mm",
         "shared pattern, boards concentric"),
        ("board envelope", "45.10 x 46.10 mm",
         f"{F_CAD_W:.2f} mm clear per side, {F_CAD_L:.2f} mm at the nearer end"),
        ("motor pattern",
         f"{design.MOTOR_JOINT['pitch_mm']:.0f} x "
         f"{design.MOTOR_JOINT['pitch_mm']:.0f} mm",
         "[D] BrotherHobby product data; one source, `design.MOTOR_JOINT`"),
        ("propeller diameter", f"{P['dia_mm']:.1f} mm", "7 in"),
        ("adjacent propeller gap", f"**{prop_gap:.1f} mm**",
         f"{F['wb']:.0f} mm wheelbase, discs {motor_off*2:.1f} mm apart"),
        ("camera lens to skid contact", f"{cam_margin:.1f} mm",
         f"{S['drop']:.0f} mm drop + {S['t']:.1f} mm pad - {C['mod_t']:.0f} mm module "
         f"- {C['lens_len']:.1f} mm barrel; the skid is PRINTED, so drop and thickness "
         f"are design values, not measurements"),
        ("battery envelope", f"{B['L']} x {B['W']} x {B['H']} mm",
         "plan view only - restraint and CG are physical checks"),
        ("companion board", "NOT FITTED",
         "65 x 30 mm Radxa vs a 47 mm battery on a 50 mm plate - see docs/SENSORS.md"),
    ]
    out = ["| feature | value | note |", "|---|---|---|"]
    out += [f"| {a} | {b} | {c} |" for a, b, c in rows]
    out.append("")
    out.append("Interference is not asserted here: `tools/check_cad_fit.py` exports every "
               "part of `cad/drone.scad` and measures the **intersection volume** of all "
               f"{npairs()} pairs, plus their minimum separation.")
    return "\n".join(out)


def stack_table():
    """Every level of the stack, computed from the board and design.py."""
    sys.path.insert(0, str(REPO / "tools"))
    import design
    s = load_standoff()
    F, E, M = design.FRAME, design.ESC, design.MOUNTING
    z = 0.0
    rows = [["level", "height", "source"], ["---", "---", "---"]]
    def step(name, dz, src):
        nonlocal z
        z += dz
        rows.append([name, f"{z:.2f} mm", src])
    fsrc = F["src"].split(";")[0]
    step("top of the bottom plate", F["bottom_t"], fsrc)
    step("top of the arms", F["arm_t"], fsrc)
    step("top of the mid plate - **the stack bolts here**", F["medium_t"], fsrc)
    step("top of the ESC's PCB", E["pcb"], E["src"])
    step("top of the ESC's tallest part", E["parts"], E["src"])
    step(f"bottom of this board's tallest bottom part (`{s['botref']}`)",
         M["gap"], M["src"])
    step("underside of this board's PCB", s["bot"], "[M] board")
    step("top surface of this board", design.BOARD_T, "[D] 6-layer stackup from JLCPCB")
    step(f"top of the tallest part (`{s['topref']}`)", s["top"], "[M] board")
    rows.append([f"**standoff to buy - {s['buy']} mm**", f"{s['buy']:.2f} mm", s["src"]])
    rows.append(["**SPARE**", f"{s['buy'] - z:.2f} mm", "[M] derived"])
    return "\n".join("| " + " | ".join(r) + " |" for r in rows)


def frame_table(f):
    _sto = load_standoff()
    rows = [
        "| | value | ",
        "|---|---|",
        f"| structure / wheelbase | X-type, {f['wb']:.0f} mm |",
        f"| overall size | {f['size'][0]} x {f['size'][1]} mm - the "
        "**frame footprint, not the centre plate** |",
        f"| plates | bottom {f['bottom_t']}, medium {f['medium_t']}, "
        f"upper {f['upper_t']}, camera side {f['cam_plate_t']} mm |",
        f"| arms | {f['arm_t']} mm |",
        f"| **FC mounting** | **{f['stack']}** |",
        f"| **inner space over the mid plate** | **{f['inner_h']:.0f} mm** - the kit's "
        f"22 mm front standoffs; 30 mm rear standoffs stand on the bottom plate "
        f"(design.TOP_PLATE_MOUNT, from the DXF) |",
        f"| **standoffs** | **use the kit's** - stack {_sto['stack']:.1f} mm leaves "
        f"{_sto['slack']:.1f} mm under the top plate |",
        f"| motor mounting | {' / '.join(f'{p:.0f}x{p:.0f}' for p in f['motor_patterns_mm'])} mm "
        f"([L] retailer figure - the manufacturer DXF's motor holes are self-inconsistent, "
        f"see KNOWN-ISSUES.md) |",
        f"| included | frame kit + one {f['strap'][0]:.0f} x {f['strap'][1]:.0f} mm "
        "battery strap |",
        f"| mass / price | {f['g']:.0f} g / GBP {f['price_gbp']:.2f} |",
        "",
        f"Source: {f['src']}",
        "",
        "Generated from `FRAME` in `tools/design.py` by `tools/gen_doc_tables.py`; "
        "do not edit it here. Two earlier frames were specified from listings that "
        "disagreed with each other - the arm thickness and standoff height feed real "
        "outputs (motor screw length and stack clearance), so both were wrong "
        "downstream. This frame's numbers come from the manufacturer's published DXF.",
    ]
    return "\n".join(rows)


def module_table():
    """The modularity map, from design.MODULES."""
    sys.path.insert(0, str(REPO / "tools"))
    import design
    mods = {k: v for k, v in design.MODULES.items() if isinstance(v, dict)}
    now = {k: v for k, v in mods.items() if v["needs_board_change"] is None}
    later = {k: v for k, v in mods.items() if v["needs_board_change"] is not None}

    out = [f"**{len(now)} of {len(mods)} modules attach to the board exactly as it will be "
           "fabricated.** No respin, no cut traces, no adapter board.", "",
           "| module | what | attaches to | status | £ |", "|---|---|---|---|---|"]
    for k, m in sorted(now.items(), key=lambda kv: (kv[1]["status"] != "fitted", kv[0])):
        out.append(f"| `{k}` | {m['what']} | {m['conn']} | {m['status']} | {m["gbp"]} |")

    out += ["", f"### The {len(later)} that would need a second fabrication run", "",
            "Neither is on the critical path, and neither blocks a capability outright:",
            "", "| module | what a respin would have to change | why it is not urgent |",
            "|---|---|---|"]
    for k, m in sorted(later.items()):
        out.append(f"| `{k}` | {m['needs_board_change']} | {m['note']} |")
    rail = design.RAIL_5V
    budget = rail["headroom_a"] * 1000
    unc = sorted(((n, m["ma_5v"]) for n, m in mods.items()
                  if not m["counted"] and m["ma_5v"]), key=lambda x: -x[1])
    tot = sum(ma for _, ma in unc)
    out += ["", "### They attach. They cannot all run at once.", "",
            f"Attaching and powering are different questions, and the +5 V rail answers the "
            f"second one more strictly. `L2` is rated **{rail['irms_a']} A RMS** and the "
            f"fully-fitted load in `check_build.LOADS_5V` is already "
            f"**{rail['fitted_load_a']:.3f} A**, leaving **{budget:.0f} mA**:", "",
            "| module not yet in that budget | draw |", "|---|---|"]
    out += [f"| `{n}` | {ma} mA |" for n, ma in unc]
    out += [f"| **total** | **{tot} mA** |", "",
            f"**{tot} mA offered against {budget:.0f} mA available.** Fit one or two, or give "
            "one its own BEC off the battery — which is the right answer for anything with "
            "real transients anyway. This is a **power** limit, not an interface limit: every "
            "module above still lands on a real pad.", "",
            "Generated by `tools/gen_doc_tables.py` from `design.MODULES` and "
            "`design.RAIL_5V`; do not edit it here."]
    return "\n".join(out)


def fastener_tables():
    """Whatever `fasteners.py --md` prints, verbatim."""
    r = subprocess.run([sys.executable, str(REPO / "tools" / "fasteners.py"), "--md"],
                       capture_output=True, text=True, cwd=REPO)
    if r.returncode != 0:
        raise SystemExit(f"FAIL: fasteners.py --md exited {r.returncode}\n{r.stderr}")
    return (r.stdout.strip() + "\n\nGenerated by `tools/gen_doc_tables.py` from "
            "`tools/fasteners.py`; do not edit it here.")


STAGES = [
    ("A1", "The board, and its bench",
     "Power it, flash it, prove it - no aircraft. Runbook Parts 7-10 (T1-T3a)."),
    ("A2", "Iridium navigation, no aircraft",
     "The receive chain the board cannot supply, and the bench reference receiver "
     "for T3b step 1. The tuner (U13) is on the board; this is what feeds it."),
    ("B1", "The aircraft - minimum to fly on GPS",
     "Frame, propulsion, radio, GPS, fasteners, looms. Every optional sensor ships "
     "disabled, so nothing in B2 is needed for a GPS flight."),
    ("B2", "Aircraft sensors and payload - optional",
     "`RNGFNDn_TYPE` and `PRX1_TYPE` ship at 0; enable each one at the bench after it "
     "is fitted. The +5 V rail cannot carry all of these AND the SAWbird+ at once - "
     "`check_modules.py` prints the budget."),
]


def _parts():
    import csv
    rows = list(csv.DictReader(open(REPO / "docs" / "PARTS.csv")))
    cost_key = next(k for k in rows[0] if "USD" in k or "Indicative" in k)

    def money(r):
        try:
            return float(r[cost_key] or 0)
        except ValueError:
            return 0.0
    return rows, money


def _tag_of(r):
    s = r["Provenance"].strip()
    return ("**[A]**" if s.startswith("ASSUMED") else
            "[D]" if s.startswith(("DATASHEET", "[D]")) else
            "[L]" if s.startswith(("LISTING", "[L]")) else
            "[M]" if s.startswith(("MEASURED", "[M]")) else "[?]")


def _price_tag(r):
    """Whether the price is quoted or guessed - a different question from whether the spec
    is verified, and previously conflated with it. A link to a search page means the
    number beside it is an estimate nobody has checked against a real listing.
    """
    u = r["Link"].strip()
    return "~est" if ("/w/" in u or "wholesale" in u or u in ("-", "")) else "quoted"


def order_sheet():
    """The shopping list, generated from docs/PARTS.csv rather than hand-written."""
    rows, money = _parts()
    buy = [r for r in rows if r["Status"].strip() in ("TO BUY", "BUY", "PRINT")]
    have = [r for r in rows if r["Status"].strip() == "HAVE"]
    later = [r for r in rows if r["Status"].strip() in ("LATER", "DEFERRED", "CONSIDER")]
    stage_of = lambda r: (r.get("Stage") or "-").strip()

    out, total, n = [], 0.0, 0
    subtotals = {}
    for code, name, blurb in STAGES:
        grp = [r for r in buy if stage_of(r) == code]
        own = [r for r in have if stage_of(r) == code]
        if not grp and not own:
            continue
        sub = sum(money(r) for r in grp)
        subtotals[code] = sub
        total += sub
        out += [f"**{code} — {name}** — {len(grp)} lines, ~GBP {sub:.0f}", "", blurb, "",
                "| # | item | qty | ~GBP | price | source | spec |",
                "|---|---|---:|---:|---|---|---|"]
        for r in grp:
            n += 1
            out.append(f"| {n} | {r['Item']} | {r['Qty']} | {money(r):.0f} | "
                       f"{_price_tag(r)} | {r['Source']} | {_tag_of(r)} |")
        if own:
            out.append("")
            out.append("Already have: " + ", ".join(r["Item"] for r in own) + ".")
        out.append("")
    a = subtotals.get("A1", 0) + subtotals.get("A2", 0)
    out += [f"**TOTAL {len(buy)} lines, ~GBP {total:.0f}.** "
            + " ".join(f"{k} ~GBP {v:.0f}." for k, v in subtotals.items()),
            "",
            f"**The board and Iridium navigation with no aircraft is A1 + A2: ~GBP {a:.0f}.** "
            f"A GPS-flying aircraft adds B1 (~GBP {subtotals.get('B1', 0):.0f}); B2 is "
            "optional and each item is enabled at the bench after it is fitted.", "",
            "Two separate columns, because they are two separate questions. **price** "
            "`quoted` means the link goes to a real product listing; `~est` means it goes "
            "to a search page and the number beside it is an estimate nobody has checked. "
            "**spec** **[A]** means the part's specification is assumed rather than "
            "sourced. A line can be quoted-but-assumed or estimated-but-datasheeted; "
            "conflating them hides which number to go and verify.",
            "",
            "`tools/check_purchase.py` asserts every interface between two of these parts "
            "and names the ones still resting on an assumed source.",
            ""]
    if later:
        out += [f"Held back ({len(later)}): "
                + ", ".join(f"{r['Item']} (~GBP {money(r):.0f})" for r in later), ""]
    out.append("Generated from `docs/PARTS.csv` by `tools/gen_doc_tables.py`; do not edit "
               "it here. Change a part's `Status` or `Stage` in the CSV to move it.")
    return "\n".join(out)


def _tex(s):
    """Escape a CSV cell for LaTeX."""
    for a, b in (("\\", r"\textbackslash{}"), ("&", r"\&"), ("%", r"\%"), ("$", r"\$"),
                 ("#", r"\#"), ("_", r"\_"), ("{", r"\{"), ("}", r"\}"), ("~", r"\textasciitilde{}"),
                 ("^", r"\textasciicircum{}")):
        s = s.replace(a, b)
    return s


def runbook_order():
    """The same staged list as a LaTeX longtable, spliced into docs/navcore-runbook.tex."""
    rows, money = _parts()
    buy = [r for r in rows if r["Status"].strip() in ("TO BUY", "BUY", "PRINT")]
    have = [r for r in rows if r["Status"].strip() == "HAVE"]
    stage_of = lambda r: (r.get("Stage") or "-").strip()
    out = []
    total = 0.0
    for code, name, blurb in STAGES:
        grp = [r for r in buy if stage_of(r) == code]
        own = [r for r in have if stage_of(r) == code]
        if not grp and not own:
            continue
        sub = sum(money(r) for r in grp)
        total += sub
        out += [r"\subsubsection*{" + _tex(f"{code} --- {name}") + r"} " +
                _tex(f"{len(grp)} lines, about GBP {sub:.0f}."),
                _tex(blurb.replace("`", "")), "",
                r"\begin{longtable}{@{}P{0.50\textwidth}P{0.12\textwidth}rP{0.22\textwidth}@{}}",
                r"\toprule", r"\textbf{Item} & \textbf{Qty} & \textbf{GBP} & \textbf{Source} \\ \midrule", r"\endhead",
                r"\bottomrule", r"\endfoot"]
        for r in grp:
            out.append(f"{_tex(r['Item'])} & {_tex(r['Qty'])} & {money(r):.0f} & {_tex(r['Source'])} \\\\")
        out.append(r"\end{longtable}")
        if own:
            out.append(_tex("Already have: " + ", ".join(r["Item"] for r in own) + "."))
        out.append("")
    out.append(_tex(f"Total, everything to buy: about GBP {total:.0f}. ") +
               r"Generated from \file{docs/PARTS.csv} by \file{tools/gen\_doc\_tables.py}; " +
               r"every row's reasoning and link is in the CSV, and \file{docs/BUYING.md} is the same list with prices and provenance tags.")
    return "\n".join(out)


def _splice(path, begin, end, body, what, check):
    text = path.read_text()
    if begin not in text or end not in text:
        print(f"FAIL: {path} has no {begin} / {end} markers")
        return 1, text
    head, rest = text.split(begin, 1)
    _, tail = rest.split(end, 1)
    new = f"{head}{begin}\n{body}\n{end}{tail}"
    if new == text:
        print(f"{what} is current")
        return 0, text
    if check:
        print(f"FAIL: {path.name} {what} is stale - run tools/gen_doc_tables.py")
        return 1, text
    path.write_text(new)
    print(f"rewrote the {what} in {path}")
    return 0, new


def cross_doc_totals(check):
    """docs/BENCHMARK.md quotes the order total. Assert it against the generated one."""
    import csv as _csv, re as _re
    rows = list(_csv.DictReader(open(REPO / "docs" / "PARTS.csv")))
    def _money(r):
        v = (r.get("Indicative USD (LINE TOTAL, not unit)") or "").strip()
        try: return float(_re.sub(r"[^0-9.]", "", v) or 0)
        except ValueError: return 0.0
    total = round(sum(_money(r) for r in rows
                      if (r.get("Status") or "").strip().upper() == "TO BUY"))
    txt = (REPO / "docs" / "BENCHMARK.md").read_text()
    m = _re.search(r'\*\*GBP\s*([\d,]+) airframe', txt) or \
        _re.search(r'\*\*\u00a3([\d,]+) airframe', txt)
    if not m:
        print("  cross-doc totals: no airframe cost figure found in BENCHMARK.md")
        return 1
    quoted = int(m.group(1).replace(",", ""))
    if quoted == total:
        print(f"  cross-doc totals: BENCHMARK.md airframe cost {quoted} matches "
              f"the generated order sheet")
        return 0
    print(f"  cross-doc totals: BENCHMARK.md says {quoted} but PARTS.csv 'TO BUY' "
          f"sums to {total}" + ("" if check else " - FIX IT BY HAND, this is prose"))
    return 1


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    rc = 0
    rc |= _splice(REPO / "sitl" / "README.md", SCEN_BEGIN, SCEN_END,
                  table(load_scenarios()), "scenario table", args.check)[0]
    rc |= _splice(REPO / "docs" / "HARDWARE.md", FRAME_BEGIN, FRAME_END,
                  frame_table(load_frame()), "frame table", args.check)[0]
    rc |= _splice(REPO / "docs" / "BUYING.md", SPATIAL_BEGIN, SPATIAL_END,
                  spatial_table(), "spatial table", args.check)[0]
    rc |= _splice(REPO / "docs" / "HARDWARE.md", STACK_BEGIN, STACK_END,
                  stack_table(), "stack table", args.check)[0]
    rc |= _splice(REPO / "docs" / "HARDWARE.md", FAST_BEGIN, FAST_END,
                  fastener_tables(), "fastener table", args.check)[0]
    rc |= _splice(REPO / "docs" / "MODULES.md", MODULE_BEGIN, MODULE_END,
                  module_table(), "module table", args.check)[0]
    rc |= _splice(REPO / "docs" / "navcore-runbook.tex", TEX_ORDER_BEGIN, TEX_ORDER_END,
                  runbook_order(), "runbook buy list", args.check)[0]
    rc |= _splice(REPO / "docs" / "BUYING.md", ORDER_BEGIN, ORDER_END,
                  order_sheet(), "order sheet", args.check)[0]
    rc |= cross_doc_totals(args.check)
    return rc


if __name__ == "__main__":
    raise SystemExit(main())
