#!/usr/bin/env python3
"""Merge MatekH743 hwdef + NAVCORE-SoOP deltas -> docs/PINMAP.md (single source of truth)."""
import json, sys, os
sys.path.insert(0, os.path.dirname(__file__))
from hwdef_pinmap import parse, sort_key

HW = "firmware/reference/MatekH743-hwdef.dat"
pins, alts = parse(HW)
d = json.load(open("tools/navcore_deltas.json"))
re_map, notes = d["revB_reassign"], d["board_notes"]

rows = []
for p in sorted(pins, key=sort_key):
    e = pins[p]
    revA = e["label"]
    revB = re_map[p]["to"] if p in re_map else revA
    note = notes.get(p, "")
    if not note:
        for k, v in notes.items():
            if p in k.split("/") or (("-" in k) and p == k.split("-")[0]):
                note = v; break
    if p in re_map and not notes.get(p):
        note = (note + " " if note else "") + f"**SoOP config**: {re_map[p]['why']}"
    rows.append((p, revA, revB, e["periph"], " ".join(e["opts"]), note))

out = ["# NAVCORE-SoOP — pin map",
       "",
       "**Generated by `tools/gen_pinmap.py` — do not hand-edit.**",
       "Sources: `firmware/reference/MatekH743-hwdef.dat` + `tools/navcore_deltas.json`.",
       "Regenerate after changing either: `python3 tools/gen_pinmap.py`",
       "",
       "## There is ONE board",
       "",
       "This project has **a single PCB**, fabricated once. There are two",
       "*firmware configurations* of that one board:",
       "",
       "| configuration | what it is |",
       "|---|---|",
       f"| **default** | bit-identical to MatekH743 across all {len(pins)} assigned pins, so stock ArduPilot `MatekH743` binaries run **unmodified** |",
       f"| **SoOP** | the same board with **{len(re_map)} pins repurposed in firmware**, plus a tuner wired to pads that already exist |",
       "",
       f"All {len(re_map)} repurposed pins are MatekH743 functions this airframe does not have, and each",
       "already reaches a pad — so **there is no PCB change between the two**. Switching",
       "configuration is a reflash, not a fabrication run.",
       "",
       "| Pin | default signal | SoOP signal | Periph | Options | Note |",
       "|---|---|---|---|---|---|"]
for p, a, b, per, o, n in rows:
    bcell = f"**{b}**" if a != b else b
    out.append(f"| `{p}` | {a} | {bcell} | {per} | {o} | {n} |")

out += ["", "## SoOP configuration — the repurposed pins", "",
        "| Pin | MatekH743 use | NAVCORE-SoOP use | Why it is free |", "|---|---|---|---|"]
for p, v in re_map.items():
    out.append(f"| `{p}` | {v['was']} | **{v['to']}** | {v['why']} |")

out += ["", "## MatekH743 features deliberately not populated", ""]
out += [f"- {x}" for x in d["unpopulated_matek_features"]]
out += ["", f"Total pins assigned: **{len(pins)}**. "
            f"Alternate-function pins: **{len(alts)}** "
            f"({', '.join(sorted(alts, key=sort_key))}).", ""]

os.makedirs("docs", exist_ok=True)
open("docs/PINMAP.md", "w").write("\n".join(out))
print(f"docs/PINMAP.md written: {len(rows)} pins, {len(re_map)} repurposed pins")
