#!/usr/bin/env python3
"""
Generate the ArduPilot hwdef for this board from the vendored MatekH743 reference.

The board is pin-identical to MatekH743 across all 75 assigned pins, so the hwdef is
that file plus a small, explicit delta rather than a fresh transcription - the same
reason docs/PINMAP.md is generated. Anything hand-typed here could drift from the
schematic; anything derived cannot.

Writes firmware/NAVCORE_SoOP/{hwdef.dat, hwdef-bl.dat}.
"""
import os, sys, re
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import design

REF   = "firmware/reference/MatekH743-hwdef.dat"
REFBL = "firmware/reference/MatekH743-hwdef-bl.dat"
OUT   = "firmware/NAVCORE_SoOP"
PCB   = "NAVCORE-SoOP.kicad_pcb"

BOARD_ID = 9001          # 9000-9099 was clear in Tools/AP_Bootloader/board_types.txt

HEADER = """# hwdef for NAVCORE-SoOP
#
# GENERATED by tools/gen_hwdef.py from the vendored MatekH743 reference plus the
# deltas below. Do not hand-edit - change tools/gen_hwdef.py or design.py instead.
#
# The board is pin-identical to MatekH743 across all 75 assigned pins, which is the
# whole point: stock ArduPilot MatekH743 binaries run on it unmodified for bring-up.
# This file exists to give it its own board ID and to describe only the hardware that
# is actually populated.
#
# NOTE: board ID {bid} is NOT registered with ArduPilot. It is free in
# Tools/AP_Bootloader/board_types.txt today, but must be requested upstream before
# this board is shared or sold.
""".format(bid=BOARD_ID)

# Lines to drop: hardware MatekH743 has that this board does not populate.
DROP = [
    (r'^PB12 MAX7456_CS',        "no analogue OSD fitted"),
    (r'^SPIDEV osd ',            "no analogue OSD fitted"),
    (r'^define OSD_ENABLED',     "no analogue OSD fitted"),
    (r'^define HAL_OSD_TYPE_DEFAULT', "no analogue OSD fitted"),
    (r'^ROMFS_WILDCARD libraries/AP_OSD', "no analogue OSD fitted"),
    (r'^PA4 BATT2_VOLTAGE_SENS', "single battery; freed for the Rev B I/Q input"),
    (r'^PC4 PRESSURE_SENS',      "no airspeed sensor; freed for the Rev B I/Q input"),
    (r'^PC5 RSSI_ADC',           "RSSI arrives over CRSF; freed for the Rev B AGC readback"),
    (r'^define HAL_BATT2_',      "single battery"),
    (r'^define HAL_DEFAULT_AIRSPEED_PIN', "no airspeed sensor"),
    (r'^define BOARD_RSSI_ANA_PIN', "RSSI arrives over CRSF"),
    (r'^BARO DPS310',            "DPS310 is not stocked at LCSC; MS5611 fitted"),
    (r'^BARO BMP280',            "BMP280 not fitted"),
    (r'^IMU Invensense SPI:icm20602', "ICM-20602 not fitted"),
    (r'^IMU Invensense SPI:mpu6000',  "MPU6000 not fitted"),
    (r'^SPIDEV icm20602',        "ICM-20602 not fitted"),
    (r'^SPIDEV mpu6000',         "MPU6000 not fitted"),
    (r'^PE1 UART8_TX',
     "ESC telemetry is receive-only, so UART8 needs only PE0/RX. PE1 is left "
     "unwired rather than declared and unconnected"),
]

# Lines to rewrite: pins MatekH743 uses for something else, which this board wires to
# real hardware. Dropping them is not enough - the pin still has to be declared, just
# declared correctly. Direction and reset level are the whole point here, and
# tools/check_pin_semantics.py enforces the result against design.PIN_INTENT.
REPLACE = [
    (r'^PD10\s+PINIO1',
     "PD10 VL53L1X_INT INPUT PULLUP GPIO(81)",
     "PD10 carries the VL53L1X's GPIO1, which is the SENSOR's interrupt output - "
     "MatekH743 has a spare user GPIO here and declares it OUTPUT, which would put the "
     "MCU and the sensor on the same node both driving. Open-drain part, so PULLUP."),
    (r'^PA7 BATT2_CURRENT_SENS',
     "PA7 VTX_EN OUTPUT LOW GPIO(83)",
     "MatekH743 reads PA7 as BATT2_CURRENT_SENS. This board has one battery, so the pin "
     "was free, and it now drives Q3's gate to switch the 9 V VTX rail. LOW leaves the "
     "rail enabled - R45 pulls the gate down as well - so the VTX fails safe towards "
     "powered. It is deliberately a pin MatekH743 only ever READS: a stock MatekH743 "
     "binary cannot assert it and so cannot cut video."),
    (r'^PD11\s+PINIO2',
     "PD11 VL53L1X_XSHUT OUTPUT HIGH GPIO(82)",
     "PD11 drives the VL53L1X's XSHUT, and the part runs only while XSHUT is HIGH. "
     "R13 pulls it up; MatekH743's OUTPUT ... LOW drove against that pull-up and held "
     "the rangefinder in shutdown from the moment the firmware booted."),
]

EXTRA = """
# ---------------------------------------------------------------- this board ---
# Populated sensors, and nothing else - an unpopulated probe just wastes boot time.
#   IMU1  ICM-42688-P on SPI1   (LCSC C1850418)
#   IMU2  ICM-42605   on SPI4   (LCSC C2655099)
#   BARO  MS5611      on I2C2 @ 0x77  (LCSC C15639)
# MS5611 CSB is tied to GND, which per the datasheet puts it at 0x77 - the address
# MatekH743 already declares, so this needed no firmware change.

# W25Q128 on SPI3 EXT_CS2 - holds the Iridium TLE catalogue, not firmware.
SPIDEV tle_flash  SPI3 DEVID2 EXT_CS2 MODE3 8*MHZ 32*MHZ

# No on-board compass by design: a magnetometer 15 mm from a 60 A 4-in-1 ESC is
# useless. I2C1 is on the GPS connector - use the compass inside the GPS module.
define ALLOW_ARM_NO_COMPASS 1
"""

# ---------------------------------------------------------------- defaults ---
# ArduPilot picks up a defaults.parm sitting beside hwdef.dat automatically and bakes
# it into ROMFS - the build says "No default parameter file found" when it is missing,
# which it was. Without one, a freshly flashed board has no idea it has a rangefinder,
# an optical flow sensor, an ESC telemetry link or a DShot ESC, and every one of those
# has to be typed in by hand before the aircraft is useful.
#
# Values that can be DERIVED are derived - BATT_VOLT_MULT comes from the resistors in
# design.py, so changing the divider changes the parameter. Values that genuinely
# cannot be known offline are marked and left at a safe default rather than invented.
#
# Enum values below were read out of the ArduPilot source, not remembered:
#   FLOW_TYPE 2      = Pixart          (8 is UPFLOW - an easy and expensive mistake)
#   RNGFND1_TYPE 16  = VL53L0X/VL53L1X
#   SERIAL protocol  5 = GPS, 16 = ESC Telemetry, 23 = RCIN, 2 = MAVLink2
#   NTF_LED_TYPES    bit 0 built-in + bit 8 NeoPixel = 257
#   SERVO13_FUNCTION 120 = k_LED_neopixel1, and PA8 is PWM(13)

def defaults_parm():
    import design as _d
    def ohms(ref):
        v = _d.COMPONENTS[ref][2]
        m = re.fullmatch(r"(\d+)(R|k|M)?(\d*)", v)
        num = float(f"{m.group(1)}.{m.group(3)}" if m.group(3) else m.group(1))
        return num * {"R": 1, None: 1, "k": 1e3, "M": 1e6}[m.group(2)]
    mult = (ohms("R18") + ohms("R19")) / ohms("R19")
    return f"""# Default parameters for NAVCORE-SoOP.
# GENERATED by tools/gen_hwdef.py - do not hand-edit.
#
# Serial ports follow SERIAL_ORDER in hwdef.dat:
#   SERIAL0  OTG1    USB console
#   SERIAL1  UART7   companion computer   (pads P42 TX / P43 RX / P45 RTS)
#   SERIAL2  USART1  telem2               (test pads TP5 / TP6)
#   SERIAL3  USART2  GPS + external compass (J3)
#   SERIAL4  USART3  not wired on this board
#   SERIAL5  UART8   ESC telemetry        (J2.8, receive-only)
#   SERIAL6  UART4   spare                (pads P72 / P73)
#   SERIAL7  USART6  RC input             (J5 / pads P52, P53)
#   SERIAL8  OTG2    SLCAN

# --- airframe -------------------------------------------------------------
FRAME_CLASS 1
FRAME_TYPE 1

# --- motors: DShot600 into the SpeedyBee 4-in-1 ---------------------------
MOT_PWM_TYPE 6

# --- serial ---------------------------------------------------------------
SERIAL1_PROTOCOL 2
SERIAL1_BAUD 921
SERIAL3_PROTOCOL 5
SERIAL5_PROTOCOL 16
SERIAL5_BAUD 115
SERIAL7_PROTOCOL 23

# --- battery --------------------------------------------------------------
# 4 = Analog Voltage and Current. hwdef sets HAL_BATT_MONITOR_DEFAULT to the same value;
# stating it here too makes the file self-describing and survives a hwdef edit.
BATT_MONITOR 4
# BATT_VOLT_MULT is the fitted divider: {_d.COMPONENTS['R18'][2]} / {_d.COMPONENTS['R19'][2]}.
BATT_VOLT_MULT {mult:.3f}
# DERIVED FROM THE ESC'S OWN MANUAL, and it used to be about 2x wrong.
#
# SpeedyBee publish the BLS 60A's current sensor as "Scale=400 Offset=0". That scale is
# Betaflight's, in units of 0.1 mV/A, so 400 = 40.0 mV/A = 0.0400 V/A, and ArduPilot's
# amps-per-volt is the reciprocal: 1 / 0.0400 = 25.0.
#
# This board applies NO scaling of its own - design.py routes ESC_CUR straight from J2.7
# to U1.PC1 through a filter cap only - so the ESC's figure governs directly. At the ESC's
# 60 A continuous that is 2.4 V into a 3.3 V ADC, which is why no divider is fitted.
#
# The previous value here was 52.7, taken from an ArduPilot page for a DIFFERENT SpeedyBee
# stack. Left uncorrected it would have made battery failsafe and consumed-mAh read about
# half the true figure on the first flights.
#
# STILL CALIBRATE ON THE BENCH - shunt tolerance is real - but start from the right number.
BATT_AMP_PERVLT 25.0

# --- downward rangefinder --------------------------------------------------
# TWO of them, and the order matters. See docs/SENSORS.md for the research.
#
# RNGFND1 is the Benewake TFS20-L, an OFF-BOARD module on I2C1 at 0x10 (J3.4/J3.5).
# It is the outdoor altitude source: 15 m at 100 kLux, 1.35 g. The fitted VL53L1X
# manages 3.6 m and returns roughly a third useful readings over grass, which is the
# surface this aircraft is meant to fly over.
#
# This matters more than it looks. Optical flow measures ANGULAR rate; converting it to
# a velocity needs a height, and AP_NavEKF3_OptFlowFusion.cpp degrades without range
# data. The rangefinder therefore sets the ceiling on the whole flow chain.
#
# Type 46 is the I2C driver (AP_RangeFinder.cpp:396 calls probe_i2c_buses). If the
# module you receive is UART-only, use 27 (BenewakeTF03) on SERIAL6 instead - see
# docs/SENSORS.md.
#
# If no TFS20-L is fitted, delete the RNGFND1_* block and promote RNGFND2 back to 1.
# Nothing else depends on it; the aircraft flies, but flow is bounded to ~3 m.
#
# SHIPS DISABLED. A rangefinder that is configured but not physically present fails
# prearm ("Rangefinder 1: Not Detected") and the aircraft will not arm. Found by running
# sitl/scenarios.py, not by reading the source. Set to 46 once the module is fitted;
# every other RNGFND1_ parameter below is already correct.
RNGFND1_TYPE 0
RNGFND1_ORIENT 25
RNGFND1_MIN 0.20
RNGFND1_MAX 15.00

# RNGFND2 is the on-board VL53L1X, U7, I2C1 @ 0x29. Demoted to landing and indoor work.
# RNGFND2_ADDR is NOT optional. It defaults to 0 and AP_RangeFinder passes it straight
# to get_device(bus, address), so without this the driver probes address 0 and the
# sensor is never found. 0x29 = 41 is the VL53L1X's fixed address.
#
# ALSO SHIPS DISABLED, and for a sharper reason: U7 is NOT POPULATED on the Economic
# assembly order (see docs/BUYING.md). Shipping RNGFND2_TYPE 16 would have stopped a
# freshly built aircraft from arming. Set to 16 after hand-fitting U7.
RNGFND2_TYPE 0
RNGFND2_ADDR 41
RNGFND2_ORIENT 25
RNGFND2_MIN 0.04
RNGFND2_MAX 3.60

# RNGFND3 is the TOP VL53L1X module (GY-53-L1X), an OFF-BOARD module on I2C1 at 0x29,
# facing UP for indoor ceiling avoidance. ORIENT 24 (ROTATION_PITCH_90) is what lets
# AP_Proximity_RangeFinder feed AC_Avoid's upward check - but ONLY once PRX1_TYPE 4 is
# set, which belongs with the MCU sensor hub (docs/SENSORS.md). Until then the upward
# module is fitted and readable but does nothing.
#
# The 0x29 clash with RNGFND2/U7 is NOT REAL: U7 is DNP on the Economic order, so the
# address is free. Fit one or the other - never both.
#
# RNGFND3_ADDR is NOT optional, exactly like RNGFND2_ADDR: it defaults to 0 and the
# driver probes address 0, never finding the sensor.
#
# SHIPS DISABLED like every rangefinder on this board: a configured but absent sensor
# fails prearm and the aircraft will not arm. Set to 16 once the module is fitted.
RNGFND3_TYPE 0
RNGFND3_ADDR 41
RNGFND3_ORIENT 24
RNGFND3_MIN 0.04
RNGFND3_MAX 3.60

# --- optical flow ---------------------------------------------------------
# FLOW_TYPE 5 = MAVLink: flow arrives as OPTICAL_FLOW messages from the companion
# computer on SERIAL1, not from the on-board sensor.
#
# This is a deliberate demotion. FLOW_TYPE 2 (Pixart) would use U6, the PMW3901 on
# SPI3 - and correlation sensors of that class perform poorly over grass. The failure
# is texture self-similarity through a ~30x30 pixel aperture, not low light, so a
# better-lit variant does not fix it. Camera flow on the Pi has the aperture and the
# pixels to do the job.
#
# U6 remains on the board as a zero-compute fallback for tarmac and indoor flight, and
# as redundancy if the companion drops out. To use it instead, set FLOW_TYPE 2.
# (8 is UPFLOW - an easy and expensive mistake.)
#
# DO NOT SET THIS TO 0 while EK3_SRC2_VELXY or EK3_SRC3_VELXY is 5. AP_NavEKF_Source.cpp
# checks `optflow_required && !dal.opticalflow_enabled()` and refuses to arm with
# "EK3 sources require OpticalFlow". It only tests the parameter, not sensor health, so
# FLOW_TYPE 5 with no companion attached arms perfectly well - it is turning it OFF that
# grounds the aircraft.
#
# THE GENERAL RULE, which caught this design three separate times:
#   an EK3_SRCn_* entry and its backend's enable parameter are ALWAYS a pair.
#   POSXY 6 <-> VISO_TYPE     VELXY 5 <-> FLOW_TYPE     POSZ 2 <-> RNGFND1_TYPE
#   Change one without the other and the board will not arm - sometimes, as with
#   VisualOdom, not even in plain GPS flight.
FLOW_TYPE 5
# CALIBRATE ON THE BENCH. Whatever produces the flow, its X/Y axes are not necessarily
# the vehicle's - and U6 in particular is on the BOTTOM of the board. Check the sign of
# the flow output before trusting it: getting this wrong flies the aircraft away from
# where it should hold.
FLOW_ORIENT_YAW 0

# --- RC, and the ground station ------------------------------------------
# Bit 9 = CRSF, which is what ELRS speaks. Narrowed deliberately: this board's RC pads
# are specified for ELRS/CRSF. Fitting an SBUS or FPort receiver instead means setting
# RC_PROTOCOLS back to 1 (auto-detect all).
RC_PROTOCOLS 512

# THE LAPTOP GROUND STATION IS THE RC LINK. No separate telemetry radio is fitted or
# needed. ExpressLRS >= 3.5 carries MAVLink over the RC link itself, so ONE radio and ONE
# UART give both manual control and full bidirectional telemetry - live position, sensor
# data, parameter editing and mission planning in Mission Planner or QGroundControl, over
# LoRa, with better range than a SiK pair.
#
# TO ENABLE IT, change these four things from what ships above:
#     SERIAL7_PROTOCOL  23 -> 2     (MAVLink2 instead of RCIN)
#     SERIAL7_BAUD          -> 460  (460800)
#     RSSI_TYPE             -> 5
#     SR7_* streams         -> 1, except SR7_ADSB / SR7_PARAMS / SR7_RAW_CTRL which stay 0
# RC then rides INSIDE the MAVLink stream. ArduPilot needs no RC_PROTOCOLS change because
# the receiver injects RC over MAVLink rather than CRSF.
#
# IT SHIPS AS PLAIN CRSF, deliberately, for the same matched-set reason as every other
# backend on this board: MAVLink mode requires an ESP-BASED receiver on firmware >= 3.5.0.
# STM32-based ELRS receivers CANNOT do it, and many cheap ones are STM32. Shipping
# SERIAL7_PROTOCOL 2 to a board with an STM32 receiver would mean no RC at all. Switch it
# on once you have confirmed the receiver you actually bought.
#
# COST: RC gets roughly a quarter of the uplink slots in MAVLink mode, so the RC rate is
# lower than plain CRSF - around 60-125 Hz against 250-500. Fine for a cruiser, wrong for
# racing. See tools/design.py OFFBOARD["rx"].

# --- ESC telemetry and BLHeli passthrough ---------------------------------
# BLHeli passthrough - configure the ESCs through the flight controller over USB. This
# works on BLHeli_S and is how you would flash BlueJay onto them in the first place.
#
# Note that SERIAL5 / J2.8 carries no telemetry from a BLHeli_S ESC. The wire and the
# UART are correct and cost nothing; they simply have nothing to receive until a
# telemetry-capable ESC (BLHeli_32, AM32) is fitted. See docs/BUILD.md.
SERVO_BLH_AUTO 1

# --- harmonic notch -------------------------------------------------------
# MODE 1 (throttle), not mode 3 (ESC telemetry), because of what the target ESC actually
# is. The SpeedyBee "BLS" 60A is BLHeli_S, and stock BLHeli_S provides NO RPM AT ALL:
# it has no telemetry wire (the ESC end of the 8-pin cable lists pin 8 as "N/A" in
# SpeedyBee's own manual) and stock firmware does not support bidirectional DShot either.
# Shipping mode 3 would leave the notch with no RPM source and therefore doing nothing -
# a silently useless filter on the one feature that most improves flight quality.
#
# Mode 1 tracks throttle, works with any ESC, and is a genuine improvement over a fixed
# notch. TO GET THE BETTER ONE: flash BlueJay (or AM32) onto the ESC, set
# SERVO_BLH_BDMASK 15 to enable bidirectional DShot on motors 1-4, then set
# INS_HNTCH_MODE 3. That tracks real motor RPM and is the biggest single flight-quality
# win available on this airframe.
#
# TUNE FREQ AND BW FROM A HOVER LOG. They are the floor and width, and the right values
# depend on props and KV, which this board cannot know. The values here are conservative
# and safe to fly on; they are not optimal for any particular airframe.
INS_HNTCH_ENABLE 1
INS_HNTCH_MODE 1
INS_HNTCH_REF 0.35
INS_HNTCH_FREQ 60
INS_HNTCH_BW 30
INS_HNTCH_HMNCS 3
# Bidirectional DShot on motors 1-4. Ships DISABLED: stock BLHeli_S cannot answer, and
# the rule on this board is that nothing unfitted ships enabled. Set to 15 after flashing
# BlueJay or AM32.
SERVO_BLH_BDMASK 0

# --- the GNSS-denied mode this board exists for ---------------------------
# THE SoOP FIX ARRIVES AS A SECOND GPS, NOT AS ExternalNav. That decision was made by
# measurement in sitl/, and it reversed the obvious choice.
#
# ExternalNav (VISION_POSITION_ESTIMATE, EK3_SRCn_POSXY 6) looks like the natural fit and
# CANNOT WORK HERE. AP_VisualOdom.h sets AP_VISUALODOM_TIMEOUT_MS to 300, so visual
# odometry is "healthy" only while messages arrive more often than every 300 ms - better
# than 3.3 Hz, sustained. An Iridium Doppler solution needs an observation arc across a
# satellite pass and lands at roughly 1 Hz. It can never keep VisOdom healthy, so the
# aircraft would not arm, and would flap in and out of healthy if it somehow did.
#
# AP_GPS.cpp sets GPS_TIMEOUT_MS to 4000. A GPS may go quiet for four seconds. That is
# more than 13x the tolerance, and it comfortably accommodates a 1 Hz fix.
#
# So: GPS2_TYPE 14 (MAV), and the companion sends GPS_INPUT with global lat/lon. This is
# simpler in every direction - no EKF origin to track on the Pi, no NED conversion, no
# VISO_TYPE, and RTL and waypoints work natively because the position is absolute.
#
# GPS_AUTO_SWITCH 1 (UseBest) then gives AUTOMATIC failover: when the real receiver is
# jammed or denied its fix status drops, and ArduPilot moves to the SoOP instance with no
# pilot action at all. To force the SoOP instance for testing, set GPS_AUTO_SWITCH 0 and
# GPS_PRIMARY 1.
#
# The name is GPS2_TYPE, not GPS_TYPE2. ArduPilot renamed the GPS parameters in 4.6
# (AP_GPS.cpp:280-285 registers the instances as subgroups "1_" and "2_"), and BOTH
# spellings still appear in the generated metadata because the old ones are kept as
# conversion aliases for ground stations. So a metadata check passes the old name while
# the firmware silently refuses to set it - which is exactly what happened here, and is
# why sitl/check_params_live.py now reads every parameter back from a running build.
#
# SHIPS DISABLED, like everything else that is not soldered to the board: 0 until the
# companion is fitted and streaming. See docs/SENSORS.md.
GPS2_TYPE 0
GPS_AUTO_SWITCH 1
#
# VISO_TYPE stays 0 permanently on this design - kept here to record that ExternalNav was
# evaluated and rejected on the 300 ms timeout above, so nobody re-derives it.
VISO_TYPE 0

# --- EKF source sets ------------------------------------------------------
# Because SoOP is a GPS, position needs no source switching at all: SRC1 covers both the
# real receiver and the SoOP fix. The ladder is now about losing GNSS entirely.
#
#   SRC1  GPS (real or SoOP)      normal flight and the GNSS-denied mode
#   SRC2  flow + baro             both GNSS sources gone; a hold, drifts in XY
#   SRC3  flow + baro             spare position on the switch
#
# On one RC switch via RCx_OPTION 90 ("EKF Source Set"). Assign it to a 3-position switch
# and you can drop to flow and, far more important, climb back. Never test a new source
# set where you cannot switch back.
#
# THE PAIRING RULE, which caught this design three separate times:
#   an EK3_SRCn_* entry and its backend's enable parameter are ALWAYS a pair.
#   VELXY 5 <-> FLOW_TYPE     POSZ 2 <-> RNGFND1_TYPE     POSXY 6 <-> VISO_TYPE
#   AP_NavEKF_Source.cpp validates EVERY configured set at arm time, not just the active
#   one, so a mismatch in a set you never select still grounds the aircraft - and with
#   VisualOdom it grounds it in plain GPS flight too.
EK3_SRC1_POSXY 3
EK3_SRC1_VELXY 3
EK3_SRC1_POSZ 1
EK3_SRC1_VELZ 3
EK3_SRC1_YAW 1
EK3_SRC2_POSXY 0
EK3_SRC2_VELXY 5
EK3_SRC2_POSZ 1
EK3_SRC2_VELZ 0
EK3_SRC2_YAW 1
EK3_SRC3_POSXY 0
EK3_SRC3_VELXY 5
EK3_SRC3_POSZ 1
EK3_SRC3_VELZ 0
EK3_SRC3_YAW 1

# --- VTX power switching --------------------------------------------------
# GPIO 83 is PA7 -> Q3 -> the 9 V buck's enable. Off means the FET is off, which leaves
# the rail ENABLED: video is on unless something deliberately turns it off. Assign the
# relay to an RC channel with RCx_OPTION 28 to get a switch for it.
RELAY1_FUNCTION 1
RELAY1_PIN 83
RELAY1_DEFAULT 0

# --- failsafes ------------------------------------------------------------
# This file shipped NO FS_* parameters at all. On an ordinary GPS aircraft ArduPilot's
# own defaults are right; this aircraft is deliberately not one, and SITL showed what
# that costs. From sitl/ scenario `ekf_failsafe`, on the shipped configuration:
#
#     t+40s  GPS DENIED
#     t+55s  EKF Failsafe: changed to Land Mode
#     t+55s  MODE GUIDED -> LAND
#     t+56s  EKF Failsafe Cleared
#
# Fifteen seconds after GNSS denial the aircraft put itself into LAND - on exactly the
# mission this board exists to fly. Worse, the failsafe CLEARED one second later and the
# aircraft stayed in LAND, because ArduPilot does not restore the previous mode: a
# one-second variance transient commits it to landing permanently.
#
# Three settings were MEASURED, not argued about. All three still fire the failsafe:
#
#   FS_EKF_THRESH 0.8 (stock), ACTION 1   t+55s  -> LAND
#   FS_EKF_THRESH 1.0,         ACTION 1   t+55s  -> LAND        (threshold changed nothing)
#   FS_EKF_THRESH 1.0,         ACTION 2   t+72s  -> ALT_HOLD
#
# The threshold is NOT the lever. Relaxing it from 0.8 to 1.0 produced identical
# behaviour, which says the trip is not a slow drift over a variance limit - it is a
# TRANSIENT at the GPS1 -> GPS2 handover, and it clears within about two seconds either
# way. What matters is what the aircraft does in those two seconds, and ArduPilot never
# restores the previous mode afterwards.
#
# ACTION 2 (AltHold) WAS TRIED AND IS DANGEROUS HERE. It looked like the better answer -
# AltHold is recoverable where Land is not - and the rc_loss scenario then caught what
# that costs. AltHold is a PILOT mode, and the aircraft loses its pilot:
#
#   FS_EKF_ACTION 2, rc_loss:
#     t+58s  MODE GUIDED -> ALT_HOLD      EKF failsafe
#     t+70s  RC CUT (mode was ALT_HOLD)
#     t+70s  Disarming motors             <-- DISARMED IN FLIGHT, at 12 m
#     t+73s  PreArm: Radio failsafe on
#
#   FS_EKF_ACTION 1, same scenario:
#     t+70s  RC CUT   MODE LAND -> RTL    flies home
#
# Losing the radio while in AltHold disarms the aircraft, so action 2 is off the table.
# The choice is then between 1 (stock failsafe lands) and 0 (the dead-reckon applet owns
# GPS loss instead). That was decided by running BOTH, changing nothing else:
#
#   FS_EKF_ACTION 1, rc_loss:                 FS_EKF_ACTION 0 + DR_ENABLE 1, rc_loss_dr:
#     t+70s  RC CUT (mode GUIDED)               t+53s  MODE GUIDED -> GUIDED_NOGPS
#     t+70s  MODE GUIDED -> RTL                 t+58s  MODE GUIDED_NOGPS -> RTL
#     t+78s  MODE RTL -> LAND   <-- cancelled   t+70s  RC CUT (mode was RTL)
#     t+103s ground at 0.64 m/s                 t+94s  ground at 0.73 m/s
#
# Both reach RTL, so disabling the stock failsafe costs nothing on radio loss - and only
# ACTION 0 avoids the t+78 cancellation. The reason originally given here was "because
# the applet restores the prior mode (DR_NEXT_MODE -1)". THAT REASON IS RETIRED: -1 is
# no longer shipped (see the DR_NEXT_MODE block, which measured it oscillating) and it
# was never actually in effect anyway. The real reason is simpler and does not depend on
# the applet's next-mode choice at all: on ACTION 0 the failsafe ANNUNCIATES AND TAKES NO
# ACTION, so there is no cancellation to undo. Hence 0.
#
# NOTE what this means for the test: rc_loss PASSES on ACTION 1 even though the defect
# happens, because it asserts that RTL was ENTERED, not that it survived. A green
# rc_loss was never evidence this was sound; rc_loss_dr is the scenario that shows it.
#
# ACTION 0 IS ONLY SAFE BECAUSE THE APPLET IS FITTED. If DR_ENABLE is ever set 0, or the
# script is missing from the microSD, this MUST go back to 1 - otherwise GPS loss has no
# response at all. These parameters are a MATCHED SET with FS_THR_ENABLE and DR_ENABLE
# and must never be changed one at a time: doing exactly that produced the in-flight
# disarm above.
FS_EKF_THRESH 1.0
FS_EKF_ACTION 0
#
# This does NOT fix the underlying defect, and the defect is not the action: ArduPilot
# never restores the previous mode after the failsafe clears, so a two-second transient
# ends the flight. The fix for THAT is `copter-deadreckon-home.lua`, which flies home in
# Guided_NoGPS and then commands DR_NEXT_MODE (6/RTL as shipped). See
# docs/SENSORS.md, where it is already flagged "fit this before the first GNSS-denied
# flight". Fit it, then revisit FS_EKF_THRESH against the real receiver's noise rather
# than the simulator's 180 m sigma and 2 s latency (sourced, not measured - see
# DopplerErrorModel; it was [A] 20 m until 2026-09-04).

# Radio failsafe -> RTL. Verified in sitl/ scenario `rc_loss`: with GPS denied and the
# aircraft flying on a SoOP fix, cutting the radio produced
#     MODE LAND -> RTL
# and the aircraft navigated home on a position that was NOT from GPS. That is the
# failure this aircraft is most likely to actually meet, and it works.
#
# THAT TRACE IS FROM THE ACTION 1 CONFIGURATION, and switching to ACTION 0 made rc_loss
# stop testing this. The applet now reaches RTL at ~t+60, before the harness cuts the
# radio at t+70, so the aircraft is ALREADY in RTL and there is no transition to observe;
# rc_loss reports "was already in RTL when the radio was cut" and passes on the state.
# `rc_loss_early` cuts at t+44 instead - after denial, before the applet acts - and is
# the scenario that actually exercises FS_THR_ENABLE on this configuration. If you change
# FS_THR_ENABLE, that is the one to read.
FS_THR_ENABLE 1

# GCS failsafe OFF. The only beyond-line-of-sight link this board can carry is a
# RockBLOCK on SERIAL6 (see docs/SENSORS.md), and it is HIGH_LATENCY2 only - one packet
# every RCK_PERIOD seconds. A 5-second GCS timeout against a 30-second mailbox check
# would RTL the aircraft on every single satellite gap. Turn this on only when a
# continuous telemetry link is actually fitted.
FS_GCS_ENABLE 0

# --- proximity / obstacle avoidance ---------------------------------------
# NOTHING IS SHIPPED HERE, DELIBERATELY, AND THAT IS A SAFETY CHOICE.
#
# The 360 lidar is an OFF-BOARD add-on. Enabling the backend before the hardware exists
# does not degrade gracefully - it grounds the aircraft. Measured in sitl/ scenario
# `proximity_absent`:
#
#     PRX1_TYPE 2, nothing sending OBSTACLE_DISTANCE  ->  "Arm: PRX1: No Data"
#
# So PRX1_TYPE stays 0 until the lidar is wired AND spinning. Same matched-set rule as
# FLOW_TYPE/EK3_SRC*_VELXY and RNGFND*_TYPE/EK3_SRC*_POSZ: a backend enable and the thing
# that feeds it are set together or not at all. This board has now been caught by that
# rule four separate times.
#
# TO FIT THE LDROBOT LD06 (2026-09-04 decision - it replaced the 8x VL53L1X ring and its
# TCA9548A mux, which needed MCU firmware nobody had written):
#
#     PRX1_TYPE 16          AP_Proximity_LD06 - 47-byte frame, 0x54 start, CRC8 0x4D
#     SERIAL2_PROTOCOL 11   Lidar360, on TP5 / TP6 (USART1)
#     SERIAL2_BAUD 230       230400.  An LD14P is 115200 instead - check the part
#
# Wire the lidar's TX only; leave the PWM motor input unconnected and it self-spins.
# INDOOR USE ONLY: the LD06 is rated 25 klux against ~100 klux full sun. Outdoors it
# reports phantom obstacles and AC_Avoid then brakes for nothing, which is worse than no
# sensor at all. Room lighting is 300-500 lux, so indoors it has ~50x of margin.
#
# WHAT THE LIDAR IS AND IS NOT. It is OBSTACLE AVOIDANCE - AC_Avoid stops the aircraft
# before a wall. IT IS NOT A POSITION SOURCE, and this is architectural: PRX1 feeds
# AP_Proximity -> AC_Avoid and never reaches the EKF. EK3_SRC*_POSXY accepts only
# 0=None, 3=GPS, 4=Beacon, 5=OpticalFlow, 6=ExternalNav - there is no proximity entry.
#
# So with no GNSS, no optical flow and no external navigation, the aircraft has NO
# horizontal position estimate indoors: Loiter, PosHold, RTL and Auto are unavailable and
# it flies Stabilize/AltHold under a pilot, with the lidar as a safety envelope. That is
# a deliberate, recorded choice - see docs/SENSORS.md for why ranging off walls does not
# substitute for flow, and what the SLAM route would actually cost.

# --- scripting / dead-reckon applet ---------------------------------------
# The EKF failsafe defect described above (a two-second transient ends the flight
# because ArduPilot never restores the previous mode after the failsafe clears) is
# fixed by `copter-deadreckon-home.lua`, vendored at
# firmware/NAVCORE_SoOP/sdcard/APM/scripts/ from the SAME Copter-4.7.0 tag this
# firmware is built from. It flies home in Guided_NoGPS and returns to the previous
# mode via DR_NEXT_MODE. These parameters FIT the applet; the script itself lives on
# the microSD and must be copied to APM/scripts/ at flash time.
#
# ############ READ THIS BEFORE CHANGING ANY DR_ VALUE BELOW ############
#
# THE DR_* LINES IN THIS FILE DO NOTHING. They are kept because they document the
# intended configuration and because check_params_live.py compares against them, but
# ArduPilot never applies them.
#
# The DR_* parameters do not exist until copter-deadreckon-home.lua creates them with
# param:add_param(). This file is parsed at boot, BEFORE the scripting engine starts,
# so every name here is unknown at the time and is silently discarded.
#
# Seven of the nine below happen to match the applet's own defaults, so they looked
# correct. Two did not, and the aircraft flew values nobody chose:
#
#     DR_ENABLE_DIST   this file said 30, the applet actually used 50
#     DR_NEXT_MODE     this file said -1, the applet actually used  6
#
# DR_ENABLE_DIST is the one that mattered: the applet will not arm until the aircraft
# has been that far from home with a good fix, so at 50 m it frequently never armed and
# the GPS-loss mitigation sat inert.
#
# TO CHANGE ONE OF THESE, EDIT THE add_param DEFAULT IN THE APPLET, not this file - or
# set it from the ground station after the script has run once, which persists it to
# storage. `./sitl/run_scenarios.sh --params` is the check that catches the difference;
# it now FAILS on a mismatch instead of printing a note.
#
# #######################################################################
#
# SCR_ENABLE 1: scripting must be on for the applet to run at all. Confirmed compiled
# into this board's build (SCR_ENABLE / SCR_HEAP_SIZE / SCR_VM_I_COUNT present,
# ~590 KB flash spare at last build).
SCR_ENABLE 1
# SCR_HEAP_SIZE 80000: the applet's own documented minimum. The default 41 KB is not
# enough and the script aborts at load with an out-of-memory error.
SCR_HEAP_SIZE 80000
#
# DR_ENABLE 1: arm the applet. TRIGGERS ARE PROVISIONAL - see the two below.
DR_ENABLE 1
# DR_ENABLE_DIST 30: this aircraft's rc_loss scenario flies 50+ m out; the applet must
# be armed well inside that envelope. 30 m keeps it armed on every flight the
# scenarios exercise while still requiring real distance from home.
DR_ENABLE_DIST 30
# DR_GPS_SACC_MAX 0.8 (the applet default) and DR_GPS_SAT_MIN 6 (default): BOTH ARE
# PLACEHOLDERS PENDING HARDWARE. They fire on whatever speed accuracy and satellite
# count the companion reports through GPS_INPUT - an integration property of our own
# SoOP code that cannot be predicted at a desk. The harness models SoOP as 180 m sigma
# with 2 s latency, which is an assumption, not a measurement of any real receiver.
# Tune both against the sitl/ deadreckon scenario, then re-verify against real
# GPS_INPUT quality on hardware before the first GNSS-denied flight.
DR_GPS_SACC_MAX 0.8
DR_GPS_SAT_MIN 6
# MEASURED CONSEQUENCE, recorded because it is a real in-flight behaviour and nothing
# else in this project reports it: under an INTERMITTENT fix (soop_dropout's 25% outage)
# the applet OSCILLATES. A full suite run showed deadreckon cycling
# GUIDED_NOGPS -> RTL -> GUIDED_NOGPS ten times in one flight, and ekf_failsafe seven:
#
#     t+50.2 -> GUIDED_NOGPS   t+55.4 -> RTL   t+59.6 -> GUIDED_NOGPS   t+64.9 -> RTL ...
#
# The gaps are 3.1-5.4 s against a theoretical floor of ~6 s (DR_GPS_TRIGG_SEC 3 to
# declare bad, plus the applet's own recovery_delay_ms 3000 to declare good). So the
# debounce IS working - it is being driven near its shortest possible period by a fix
# that genuinely keeps coming and going.
#
# NOT A FAILURE: every one of those runs stayed bounded and ended in RTL, which is the
# correct response. But mode chatter during a failure is alarming to a pilot and reads
# like an autopilot fault in a log, so it is written down rather than discovered later.
# To damp it, RAISE THIS VALUE - and it must be raised in the APPLET's add_param default,
# not here, for the reason given at the head of this block.
#
# DR_GPS_TRIGG_SEC 3 (applet default): GPS checks must fail this long before
# triggering. The EKF failsafe path does not wait for this timer, so a hard EKF
# event still triggers immediately.
DR_GPS_TRIGG_SEC 3
# DR_FLY_ANGLE 10 (applet default): conservative lean; most frames make max speed
# near 22 deg. Raise only after bench/hardware evidence.
DR_FLY_ANGLE 10
# DR_FLY_ALT_MIN 0: return at current altitude. The rc_loss trace holds a steady alt
# through the failsafe; climbing on dead reckoning adds risk without a measured need.
DR_FLY_ALT_MIN 0
# DR_FLY_TIMEOUT 30 (applet default): if dead reckoning lasts this long, try to
# switch to DR_NEXT_MODE anyway rather than fly blind indefinitely.
DR_FLY_TIMEOUT 30
# DR_NEXT_MODE 6 (RTL): GO HOME AND STAY THERE.
#
# This shipped -1 ("return to the mode in use before dead reckoning") with a long argument
# for it. THE ARGUMENT WAS WRONG, and it had never been tested, because DR_* parameters
# cannot be set from this file at all - see the warning at the head of this block. The
# aircraft was flying the applet's default of 6 the whole time.
#
# Measured once -1 was actually made to apply, 8 runs of soop_dropout each:
#
#     NEXT_MODE  6   diverged 3/8   reached RTL 5/8   mean 1.4 mode changes
#     NEXT_MODE -1   diverged 4/8   reached RTL 0/8   mean 6.1 mode changes
#
# -1 hands the aircraft back to whatever was flying it. For a pilot in Loiter that is
# right. For an autonomous mission - which is this aircraft's whole purpose - it hands
# control back to the thing that was flying it away, and the applet re-triggers seconds
# later; one run oscillated through 13 mode changes. Losing the position source should
# end the flight plan, not resume it.
DR_NEXT_MODE 6

# --- notify ---------------------------------------------------------------
# No safety switch is fitted, so arming must not wait for one.
BRD_SAFETY_DEFLT 0
NTF_LED_TYPES 257
SERVO13_FUNCTION 120
"""


REVB = """
# ---------------------------------------------------------- Rev B (commented) ---
# The L-band receiver lives on its own board (it did not fit here - see
# docs/LAYOUT.md). When its I/Q reaches these pins, uncomment:
#
#   PC4 SOOP_I_ADC   ADC1 SCALE(1)   # ADC1 ch4
#   PA4 SOOP_Q_ADC   ADC2 SCALE(1)   # ADC2 ch18, sampled simultaneously with PC4
#   PC5 SOOP_RSSI    ADC1 SCALE(1)   # MAX2112 AGC readback
#
# Sample PC4 on ADC1 and PA4 on ADC2 in DUAL REGULAR SIMULTANEOUS mode. Any I/Q
# sampling skew becomes a phase error, which corrupts the Doppler estimate directly.
#
# PE10 is UART7_CTS in Rev A and becomes the companion PPS sync input in Rev B.
"""


# --------------------------------------------------------- IMU orientation ---
# MatekH743 mounts its primary IMUs on the top side; the packer put ours on the
# bottom to make the density work. A part on the far side of the board is the
# top-side placement composed with a 180 deg rotation about the board Y axis, so
# the rotation MatekH743 declares is wrong for this board by exactly that much.
# Left uncorrected the vehicle flies inverted, so this is derived from the actual
# PCB rather than written down and hoped for.
#
# ArduPilot applies its rotations roll, then pitch, then yaw (AP_Math/rotations.h).

def _rot(roll, pitch, yaw):
    import math
    def mul(A, B):
        return [[sum(A[i][k] * B[k][j] for k in range(3)) for j in range(3)] for i in range(3)]
    def R(axis, d):
        c, s = round(math.cos(math.radians(d))), round(math.sin(math.radians(d)))
        return {"x": [[1, 0, 0], [0, c, -s], [0, s, c]],
                "y": [[c, 0, s], [0, 1, 0], [-s, 0, c]],
                "z": [[c, -s, 0], [s, c, 0], [0, 0, 1]]}[axis]
    return mul(R("z", yaw), mul(R("y", pitch), R("x", roll)))

# The subset of ArduPilot's enum reachable by flipping a yaw-only placement.
_NAMED = {"NONE": (0, 0, 0), "YAW_90": (0, 0, 90), "YAW_180": (0, 0, 180),
          "YAW_270": (0, 0, 270), "ROLL_180": (180, 0, 0),
          "ROLL_180_YAW_90": (180, 0, 90), "PITCH_180": (0, 180, 0),
          "ROLL_180_YAW_270": (180, 0, 270)}
_MATRIX = {n: _rot(*rpy) for n, rpy in _NAMED.items()}


def flipped_rotation(name):
    """ROTATION_<name> as declared for a top-side part, corrected for bottom-side."""
    m = _rot(0, 180, 0)
    t = _MATRIX[name]
    got = [[sum(m[i][k] * t[k][j] for k in range(3)) for j in range(3)] for i in range(3)]
    for n, R in _MATRIX.items():
        if all(got[i][j] == R[i][j] for i in range(3) for j in range(3)):
            return n
    raise SystemExit(f"flipping ROTATION_{name} is not a named ArduPilot rotation")


def imu_sides(pcb):
    """{reference: True if on the bottom} straight out of the PCB."""
    import pcbnew
    b = pcbnew.LoadBoard(pcb)
    return {f.GetReference(): f.IsFlipped() for f in b.GetFootprints()}


def _wrap(text, width=76):
    words, line, out = text.split(), "", []
    for w in words:
        if len(line) + len(w) + 1 > width:
            out.append(line); line = w
        else:
            line = f"{line} {w}".strip()
    if line:
        out.append(line)
    return out


def main():
    src = open(REF).read().split("\n")
    out, dropped, rotated, replaced = [], [], [], []
    SIDE = imu_sides(PCB)
    IMU_REF = {"icm42688": "U2", "icm42605": "U3"}
    for ln in src:
        hit = next((why for pat, why in DROP if re.match(pat, ln)), None)
        if hit:
            dropped.append((ln.strip(), hit))
            out.append(f"# [removed: {hit}] {ln}")
            continue
        rep = next((r for r in REPLACE if re.match(r[0], ln)), None)
        if rep:
            _pat, new, why = rep
            out.append(f"# [was: {ln.strip()}]")
            for chunk in _wrap(why):
                out.append(f"# {chunk}")
            out.append(new)
            replaced.append((ln.strip(), new))
            continue
        if ln.startswith("APJ_BOARD_ID"):
            out.append(f"APJ_BOARD_ID AP_HW_NAVCORE_SOOP    # {BOARD_ID}, unregistered")
            continue
        if ln.startswith("# for Matek H743-WING"):
            out.append("# for NAVCORE-SoOP (45 x 46 mm, 30.5 mm stack)")
            continue
        m = re.match(r'^IMU (\S+) (?:\w+:)?(\S+) ROTATION_(\S+)\s*$', ln)
        if m and IMU_REF.get(m.group(2)) and SIDE.get(IMU_REF[m.group(2)]):
            was = m.group(3)
            now = flipped_rotation(was)
            ref = IMU_REF[m.group(2)]
            out.append(f"IMU {m.group(1)} SPI:{m.group(2)} ROTATION_{now}"
                       f"    # {ref} is on the bottom: was ROTATION_{was} on MatekH743")
            rotated.append((ref, m.group(2), was, now))
            continue
        out.append(ln)

    body = HEADER + "\n".join(out) + EXTRA + REVB
    os.makedirs(OUT, exist_ok=True)
    open(f"{OUT}/hwdef.dat", "w").write(body)

    bl = open(REFBL).read()
    bl = re.sub(r'^APJ_BOARD_ID.*$',
                f"APJ_BOARD_ID AP_HW_NAVCORE_SOOP    # {BOARD_ID}, unregistered",
                bl, flags=re.M)
    bl = bl.replace("# for Matek H743-WING bootloader",
                    "# for NAVCORE-SoOP bootloader")
    bl = bl.replace("PB12 MAX7456_CS CS",
                    "# [removed: no analogue OSD fitted] PB12 MAX7456_CS CS")
    open(f"{OUT}/hwdef-bl.dat", "w").write(
        "# GENERATED by tools/gen_hwdef.py - do not hand-edit.\n" + bl)
    open(f"{OUT}/defaults.parm", "w").write(defaults_parm())

    print(f"wrote {OUT}/hwdef.dat, hwdef-bl.dat and defaults.parm")
    print(f"board id: AP_HW_NAVCORE_SOOP = {BOARD_ID} (unregistered)")
    print(f"lines removed from the reference: {len(dropped)}")
    for ln, why in dropped:
        print(f"   {ln[:44]:<46} {why}")
    print(f"lines rewritten for this board's hardware: {len(replaced)}")
    for was, now in replaced:
        print(f"   {was[:44]:<46} -> {now}")
    print(f"IMU rotations corrected for bottom-side mounting: {len(rotated)}")
    for ref, dev, was, now in rotated:
        print(f"   {ref} {dev:<10} ROTATION_{was} -> ROTATION_{now}")


if __name__ == "__main__":
    main()
