#!/usr/bin/env python3
"""Generate the ArduPilot hwdef for this board from the vendored MatekH743 reference."""
import os, sys, re
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import design

REF   = "firmware/reference/MatekH743-hwdef.dat"
REFBL = "firmware/reference/MatekH743-hwdef-bl.dat"
OUT   = os.environ.get("HWDEF_OUT", "firmware/NAVCORE_SoOP")
PCB   = "NAVCORE-SoOP.kicad_pcb"

BOARD_ID = 9001          # local bring-up only - request 7180 upstream, see above

HEADER = """# hwdef for NAVCORE-SoOP
# Generated by tools/gen_hwdef.py from the vendored MatekH743 reference plus the deltas below.
""".format(bid=BOARD_ID)

# Lines to drop: hardware MatekH743 has that this board does not populate.
DROP = [
    (r'^PB12 MAX7456_CS',        "no analogue OSD fitted"),
    (r'^SPIDEV osd ',            "no analogue OSD fitted"),
    (r'^define OSD_ENABLED',     "no analogue OSD fitted"),
    (r'^define HAL_OSD_TYPE_DEFAULT', "no analogue OSD fitted"),
    (r'^ROMFS_WILDCARD libraries/AP_OSD', "no analogue OSD fitted"),
    (r'^PA4 BATT2_VOLTAGE_SENS', "single battery; freed for the SoOP I/Q input"),
    (r'^PC4 PRESSURE_SENS',      "no airspeed sensor; freed for the SoOP I/Q input"),
    (r'^PC5 RSSI_ADC',           "RSSI arrives over CRSF; PC5 is spare"),
    (r'^define HAL_BATT2_',      "single battery"),
    (r'^define HAL_DEFAULT_AIRSPEED_PIN', "no airspeed sensor"),
    (r'^define BOARD_RSSI_ANA_PIN', "RSSI arrives over CRSF"),
    (r'^BARO DPS310',            "DPS310 is not stocked at LCSC; MS5611 fitted"),
    (r'^BARO BMP280',            "BMP280 not fitted"),
    (r'^IMU Invensense SPI:icm20602', "ICM-20602 not fitted"),
    (r'^IMU Invensense SPI:mpu6000',  "MPU6000 not fitted"),
    (r'^SPIDEV icm20602',        "ICM-20602 not fitted"),
    (r'^SPIDEV mpu6000',         "MPU6000 not fitted"),
    (r'^PE1 UART8_TX',
     "ESC telemetry is receive-only, so UART8 needs only PE0/RX. PE1 is left "
     "unwired rather than declared and unconnected"),
    # ---- U6 (PMW3901) and U7 (VL53L1X) are deleted -------------------------
    (r'^PD4 EXT_CS1',      "U6 (PMW3901) is deleted, the only EXT_CS1 device; PD4 freed"),
    (r'^PD10\s+PINIO1',    "U7 (VL53L1X) is deleted; PD10 freed"),
    (r'^PD11\s+PINIO2',    "U7 (VL53L1X) is deleted; PD11 freed"),
    (r'^SPIDEV pixartflow', "U6 (PMW3901) is deleted; SPI3 carries only the TLE flash"),
]

# Lines to rewrite: pins MatekH743 uses for something else, which this board wires to real hardware.
REPLACE = [
    (r'^PA7 BATT2_CURRENT_SENS',
     "PA7 VTX_EN OUTPUT LOW GPIO(83)",
     "MatekH743 reads PA7 as BATT2_CURRENT_SENS. This board has one battery, so the pin "
     "was free, and it now drives Q3's gate to switch the 9 V VTX rail. LOW leaves the "
     "rail enabled - R45 pulls the gate down as well - so the VTX fails safe towards "
     "powered. It is deliberately a pin MatekH743 only ever READS: a stock MatekH743 "
     "binary cannot assert it and so cannot cut video."),
]

EXTRA = """

# W25Q128 on SPI3 EXT_CS2 - holds the Iridium TLE catalogue, not firmware.
SPIDEV tle_flash  SPI3 DEVID2 EXT_CS2 MODE3 8*MHZ 32*MHZ

# No on-board compass by design: a magnetometer 15 mm from a 60 A 4-in-1 ESC is
# useless. I2C1 is on the GPS connector - use the compass inside the GPS module.
define ALLOW_ARM_NO_COMPASS 1

# U19, the TMP119 beside U9, needs this line or it is dead SILICON.
define AP_TEMPERATURE_SENSOR_ENABLED 1
"""

# ---------------------------------------------------------------- defaults ---

def defaults_parm():
    import design as _d
    def ohms(ref):
        v = _d.COMPONENTS[ref][2]
        m = re.fullmatch(r"(\d+)(R|k|M)?(\d*)", v)
        num = float(f"{m.group(1)}.{m.group(3)}" if m.group(3) else m.group(1))
        return num * {"R": 1, None: 1, "k": 1e3, "M": 1e6}[m.group(2)]
    mult = (ohms("R18") + ohms("R19")) / ohms("R19")
    # Derived from the ESC profile, not typed.
    amp_per_volt = 1000.0 / _d.ESC["cur_scale_mv_per_A"]
    return f"""# Default parameters for NAVCORE-SoOP.
# Generated by tools/gen_hwdef.py - do not hand-edit.

# --- airframe -------------------------------------------------------------
FRAME_CLASS 1
FRAME_TYPE 1

# --- motors: DShot600 into the SpeedyBee 4-in-1 ---------------------------
MOT_PWM_TYPE 6

# --- serial ---------------------------------------------------------------
SERIAL1_PROTOCOL 2
SERIAL1_BAUD 921
SERIAL3_PROTOCOL 5
SERIAL5_PROTOCOL 16
SERIAL5_BAUD 115
SERIAL7_PROTOCOL 23

BATT_MONITOR 4
# BATT_VOLT_MULT is the fitted divider: {_d.COMPONENTS['R18'][2]} / {_d.COMPONENTS['R19'][2]}.
BATT_VOLT_MULT {mult:.3f}
BATT_AMP_PERVLT {amp_per_volt:.1f}

RNGFND1_TYPE 0
RNGFND1_ORIENT 25
RNGFND1_MIN 0.20
RNGFND1_MAX 15.00


RNGFND3_TYPE 0
RNGFND3_ADDR 41
RNGFND3_ORIENT 24
RNGFND3_MIN 0.04
RNGFND3_MAX 3.60

FLOW_TYPE 5
# Whatever produces the flow, its X/Y axes are not necessarily the vehicle's.
FLOW_ORIENT_YAW 0

RC_PROTOCOLS 512

# No separate telemetry radio is fitted or needed.

SERVO_BLH_AUTO 1

INS_HNTCH_ENABLE 1
INS_HNTCH_MODE 1
INS_HNTCH_REF 0.35
INS_HNTCH_FREQ 60
INS_HNTCH_BW 30
INS_HNTCH_HMNCS 3
# Bidirectional DShot on motors 1-4.
SERVO_BLH_BDMASK 0

GPS2_TYPE 0
GPS_AUTO_SWITCH 1
VISO_TYPE 0

EK3_SRC1_POSXY 3
EK3_SRC1_VELXY 3
EK3_SRC1_POSZ 1
EK3_SRC1_VELZ 3
EK3_SRC1_YAW 1
EK3_SRC2_POSXY 0
EK3_SRC2_VELXY 5
EK3_SRC2_POSZ 1
EK3_SRC2_VELZ 0
EK3_SRC2_YAW 1
EK3_SRC3_POSXY 0
EK3_SRC3_VELXY 5
EK3_SRC3_POSZ 1
EK3_SRC3_VELZ 0
EK3_SRC3_YAW 1

RELAY1_FUNCTION 1
RELAY1_PIN 83
RELAY1_DEFAULT 0

FS_EKF_THRESH 1.0
FS_EKF_ACTION 0

# Radio failsafe -> RTL.
FS_THR_ENABLE 1

# GCS failsafe OFF.
FS_GCS_ENABLE 0


SCR_ENABLE 1
# SCR_HEAP_SIZE 80000: the applet's own documented minimum. The default 41 KB is not
# enough and the script aborts at load with an out-of-memory error.
SCR_HEAP_SIZE 80000
# DR_ENABLE 1: arm the applet.
DR_ENABLE 1
DR_ENABLE_DIST 30
DR_GPS_SACC_MAX 0.8
DR_GPS_SAT_MIN 6
DR_GPS_TRIGG_SEC 3
# DR_FLY_ANGLE 10 (applet default): conservative lean; most frames make max speed
# near 22 deg. Raise only after bench/hardware evidence.
DR_FLY_ANGLE 10
# DR_FLY_ALT_MIN 0: return at current altitude.
DR_FLY_ALT_MIN 0
DR_FLY_TIMEOUT 30
# DR_NEXT_MODE 6 (RTL): GO home and stay THERE.
DR_NEXT_MODE 6

# --- notify ---------------------------------------------------------------
# No safety switch is fitted, so arming must not wait for one.
BRD_SAFETY_DEFLT 0
NTF_LED_TYPES 257
SERVO13_FUNCTION 120

TEMP_LOG 1
TEMP1_TYPE 10
# Bus 1 is I2C1.
TEMP1_BUS 1
# 72 = 0x48, the TMP119 address with ADD0 tied to GND, which U19.C1 is. Parameter files
# are decimal: 0x48 written here parses as 0.
TEMP1_ADDR 72
# Source None - this is not an ESC, motor or battery temperature. It also keeps the
# reading logged under either TEMP_LOG setting.
TEMP1_SRC 0
"""


REVB = """
"""


# --------------------------------------------------------- IMU orientation ---

def _rot(roll, pitch, yaw):
    import math
    def mul(A, B):
        return [[sum(A[i][k] * B[k][j] for k in range(3)) for j in range(3)] for i in range(3)]
    def R(axis, d):
        c, s = round(math.cos(math.radians(d))), round(math.sin(math.radians(d)))
        return {"x": [[1, 0, 0], [0, c, -s], [0, s, c]],
                "y": [[c, 0, s], [0, 1, 0], [-s, 0, c]],
                "z": [[c, -s, 0], [s, c, 0], [0, 0, 1]]}[axis]
    return mul(R("z", yaw), mul(R("y", pitch), R("x", roll)))

# The subset of ArduPilot's enum reachable by flipping a yaw-only placement.
_NAMED = {"NONE": (0, 0, 0), "YAW_90": (0, 0, 90), "YAW_180": (0, 0, 180),
          "YAW_270": (0, 0, 270), "ROLL_180": (180, 0, 0),
          "ROLL_180_YAW_90": (180, 0, 90), "PITCH_180": (0, 180, 0),
          "ROLL_180_YAW_270": (180, 0, 270)}
_MATRIX = {n: _rot(*rpy) for n, rpy in _NAMED.items()}


def flipped_rotation(name):
    """ROTATION_<name> as declared for a top-side part, corrected for bottom-side."""
    m = _rot(0, 180, 0)
    t = _MATRIX[name]
    got = [[sum(m[i][k] * t[k][j] for k in range(3)) for j in range(3)] for i in range(3)]
    for n, R in _MATRIX.items():
        if all(got[i][j] == R[i][j] for i in range(3) for j in range(3)):
            return n
    raise SystemExit(f"flipping ROTATION_{name} is not a named ArduPilot rotation")


def imu_sides(pcb):
    """{reference: True if on the bottom} straight out of the PCB."""
    import pcbnew
    b = pcbnew.LoadBoard(pcb)
    return {f.GetReference(): f.IsFlipped() for f in b.GetFootprints()}


def _wrap(text, width=76):
    words, line, out = text.split(), "", []
    for w in words:
        if len(line) + len(w) + 1 > width:
            out.append(line); line = w
        else:
            line = f"{line} {w}".strip()
    if line:
        out.append(line)
    return out


def main():
    src = open(REF).read().split("\n")
    out, dropped, rotated, replaced = [], [], [], []
    SIDE = imu_sides(PCB)
    IMU_REF = {"icm42688": "U2", "icm42605": "U3"}
    for ln in src:
        hit = next((why for pat, why in DROP if re.match(pat, ln)), None)
        if hit:
            dropped.append((ln.strip(), hit))
            out.append(f"# [removed: {hit}] {ln}")
            continue
        rep = next((r for r in REPLACE if re.match(r[0], ln)), None)
        if rep:
            _pat, new, why = rep
            out.append(f"# [was: {ln.strip()}]")
            for chunk in _wrap(why):
                out.append(f"# {chunk}")
            out.append(new)
            replaced.append((ln.strip(), new))
            continue
        if ln.startswith("APJ_BOARD_ID"):
            out.append(f"APJ_BOARD_ID AP_HW_NAVCORE_SOOP    # {BOARD_ID}, unregistered")
            continue
        if ln.startswith("# for Matek H743-WING"):
            out.append("# for NAVCORE-SoOP (45 x 46 mm, 30.5 mm stack)")
            continue
        m = re.match(r'^IMU (\S+) (?:\w+:)?(\S+) ROTATION_(\S+)\s*$', ln)
        if m and IMU_REF.get(m.group(2)) and SIDE.get(IMU_REF[m.group(2)]):
            was = m.group(3)
            now = flipped_rotation(was)
            ref = IMU_REF[m.group(2)]
            out.append(f"IMU {m.group(1)} SPI:{m.group(2)} ROTATION_{now}"
                       f"    # {ref} is on the bottom: was ROTATION_{was} on MatekH743")
            rotated.append((ref, m.group(2), was, now))
            continue
        out.append(ln)

    body = HEADER + "\n".join(out) + EXTRA + REVB
    os.makedirs(OUT, exist_ok=True)
    open(f"{OUT}/hwdef.dat", "w").write(body)

    bl = open(REFBL).read()
    bl = re.sub(r'^APJ_BOARD_ID.*$',
                f"APJ_BOARD_ID AP_HW_NAVCORE_SOOP    # {BOARD_ID}, unregistered",
                bl, flags=re.M)
    bl = bl.replace("# for Matek H743-WING bootloader",
                    "# for NAVCORE-SoOP bootloader")
    bl = bl.replace("PB12 MAX7456_CS CS",
                    "# [removed: no analogue OSD fitted] PB12 MAX7456_CS CS")
    open(f"{OUT}/hwdef-bl.dat", "w").write(
        "# GENERATED by tools/gen_hwdef.py - do not hand-edit.\n" + bl)
    open(f"{OUT}/defaults.parm", "w").write(defaults_parm())

    print(f"wrote {OUT}/hwdef.dat, hwdef-bl.dat and defaults.parm")
    print(f"board id: AP_HW_NAVCORE_SOOP = {BOARD_ID} (unregistered)")
    print(f"lines removed from the reference: {len(dropped)}")
    for ln, why in dropped:
        print(f"   {ln[:44]:<46} {why}")
    print(f"lines rewritten for this board's hardware: {len(replaced)}")
    for was, now in replaced:
        print(f"   {was[:44]:<46} -> {now}")
    print(f"IMU rotations corrected for bottom-side mounting: {len(rotated)}")
    for ref, dev, was, now in rotated:
        print(f"   {ref} {dev:<10} ROTATION_{was} -> ROTATION_{now}")


if __name__ == "__main__":
    main()
