#!/usr/bin/env python3
"""
Generate cad/frame.scad from design.py, so the model and the checks cannot disagree.

cad/drone.scad used to carry its own airframe constants, and they had drifted from the
ones check_build.py was testing against:

    quantity          drone.scad   check_build   
    wheelbase            300          295.0      
    arm thickness          4.0          6.0      
    plate thickness        2.0          3.0 (bottom and medium; upper IS 2.0)
    top plate height      32           35.0 (frame inner height)

Every one of those feeds a fit answer, and which file you happened to open decided which
answer you got. This is the same defect as the bottom-side part height being written
three times in three files, and the fix is the same: one declaration, everything else
derived.

Usage: python3 tools/gen_scad_frame.py   (writes cad/frame.scad)
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import design

OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                   "cad", "frame.scad")

# MO is the MOTOR, M is the MOUNTING hardware. They used to share the name M - the
# second assignment silently won, so the generated header's "// motor :" line has been
# printing the GROMMET's provenance ("M3 silicone grommet compressed to 3.0 mm") for as
# long as the file has existed. Nothing was wrong with the geometry; the citation beside
# it named the wrong part, which is the sort of thing a reader trusts without checking.
F, MO, B, P = design.FRAME, design.MOTOR, design.BATT, design.PROP
M = design.MOUNTING
PL = design.PLATES
CR = design.CAMERA_REC
BS = design.BELLY_SENSOR
L = design.OFFBOARD["lidar"]   # LD06, [D] datasheet dimensions
E, S, C, PI = design.ESC, design.SKID, design.CAMERA, design.PI

# Stack heights are MEASURED from the board, not restated. design.stack_heights() walks
# the real footprints, so the model cannot claim a clearance the board does not have.
import pcbnew
_b = pcbnew.LoadBoard(os.path.join(os.path.dirname(os.path.dirname(
    os.path.abspath(__file__))), "NAVCORE-SoOP.kicad_pcb"))
TOP, BOT, TOPREF, BOTREF, _ = design.stack_heights(_b, skip_dnp=True)
STO = design.required_standoff(_b)
# Board size is MEASURED, not restated. Two conventions differ by the 0.1 mm Edge.Cuts
# stroke: the bounding box is 45.100 x 46.100, the centreline JLC actually routes to is
# 45.000 x 46.000. The model uses the BBOX because it is the conservative one for a fit
# check - it can only report less clearance than exists, never more. FRAME_CAD's
# 1.70 / 1.04 mm margins use the same convention.
_bb = _b.GetBoardEdgesBoundingBox()
_sw = max([d.GetWidth() / 1e6 for d in _b.GetDrawings()
           if d.GetLayer() == pcbnew.Edge_Cuts] or [0.0])
BL, BW = _bb.GetWidth() / 1e6, _bb.GetHeight() / 1e6
FAB_L, FAB_W = BL - _sw, BW - _sw
assert abs(FAB_L - design.BOARD["W"]) < 1e-6 and abs(FAB_W - design.BOARD["H"]) < 1e-6, \
    f"routed outline {FAB_L}x{FAB_W} != design.BOARD"

body = f"""// GENERATED by tools/gen_scad_frame.py - DO NOT EDIT.
// Every value comes from tools/design.py, which is the single source of truth for the
// airframe. Edit it there and regenerate, or the model and the checks drift apart again.
//
// frame : {F['src']}
// motor : {MO['src']}
// plates: {PL['src']}
// batt  : {B['src']}
// prop  : {P['src']}

wheelbase      = {F['wb']};
frame_size_x   = {F['size'][0]};
frame_size_y   = {F['size'][1]};
inner_h        = {F['inner_h']};
bottom_plate_t = {F['bottom_t']};
medium_plate_t = {F['medium_t']};
upper_plate_t  = {F['upper_t']};
arm_t          = {F['arm_t']};
cam_plate_t    = {F['cam_plate_t']};

motor_dia      = {MO['dia_mm']};
motor_h        = {MO['h_mm']};
prop_dia       = {P['dia_mm']:.1f};

batt_l = {B['L']}; batt_w = {B['W']}; batt_h = {B['H']};

// ---- PLATE OUTLINES, PARSED FROM THE MANUFACTURER DXF ---------------------
// drone.scad drew ALL THREE plates as one 50 mm square, from a variable whose own
// comment called it a placeholder ("must be >= fc_w = 46.10"). Every frame-vs-anything
// clearance check_cad_fit.py reported was therefore measured against an airframe that
// does not exist - and the error was not small or in the safe direction: the real top
// plate is 160.26 mm long, more than three times the placeholder, reaching 80 mm out
// under a prop disc of 89.2 mm radius.
//
// These are [M], flattened from So1-V6-7inDC-2025-JUL-07.dxf. The three plates are
// genuinely different shapes and the model now says so.
fc_plate_w     = {PL['fc'][0]};    // the mid plate: carries the 30.5 mm stack pattern
fc_plate_l     = {PL['fc'][1]};
top_plate_w    = {PL['top'][0]};    // carries the battery - and the battery OVERHANGS it
top_plate_l    = {PL['top'][1]};
bot_plate_w    = {PL['bottom'][0]};
bot_plate_l    = {PL['bottom'][1]};
arm_plate_w    = {PL['arm'][0]};   // widest point of an arm, at the motor end
arm_plate_l    = {PL['arm'][1]};
batt_overhang  = {PL['battery_overhang_per_side']};   // per side, battery vs top plate

// ---- STACK HEIGHTS, MEASURED FROM THE BOARD -------------------------------
// NOT hardcoded. drone.scad carried fc_bot_parts = 2.50 while design.stack_heights()
// measured 3.00 on the real board (L5, the 10 uH inductor) - so the model showed
// 0.5 mm MORE clearance to the ESC than exists. Three copies of this number have
// already disagreed once in this project (2.5 / 2.3 / 3.0); this is the fourth, and
// it is now generated so it cannot be the fifth.
fc_l           = {BL:.2f};   // Edge.Cuts bbox - conservative\nfc_w           = {BW:.2f};\nfc_l_fab       = {FAB_L:.2f};   // centreline: what JLC routes to\nfc_w_fab       = {FAB_W:.2f};
fc_pcb         = 1.60;
fc_top_parts   = {TOP};          // tallest: {TOPREF}
fc_bot_parts   = {BOT};          // tallest: {BOTREF}

esc_l          = {E['L']};
esc_w          = {E['W']};
esc_pcb        = {E['pcb']};
esc_parts      = {E['parts']};

skid_t          = {S['t']};
cam_drop        = {S['drop']};

// Nose recording camera - XIAO ESP32S3 Sense. rec_cam_y is how far forward it sits;
// the prop discs clear the nose by 24-71 mm anywhere along it, so this is free choice.
rec_cam_l       = {CR['L']};
rec_cam_w       = {CR['W']};
rec_cam_h       = {CR['H']};
rec_cam_y       = {CR['nose_y_mm']};

// Belly sensor - the downward rangefinder now, a flow+range module later. Mounts UNDER
// the bottom plate because that is the only place anything can see the ground.
belly_h         = {BS['typical_module_h']};
belly_l         = {BS['l_mm']};
belly_w         = {BS['w_mm']};

// 360 lidar (LDROBOT LD06), belly-mounted upside-down - PRX1_ORIENT 1. Dimensions are
// [D] datasheet, not guessed, and they are the reason SKID['drop'] went 25 -> 40 mm
// (35 was tried first and rejected - 5.20 mm clearance; see the SKID note in design.py):
// at 25 mm the belly had 28.5 mm of depth against a 33.30 mm lidar.
lidar_l         = {L['L_mm']};
lidar_w         = {L['W_mm']};
lidar_h         = {L['H_mm']};
lidar_y         = {L['mount_y_mm']};   // aft of the downward rangefinder at y=+18
skid_hole_pitch = {S['hole_pitch']};
gap             = {M['gap']};    // compressed grommet - [A], re-measure on assembly
grommet_dia     = {M['grommet_d']};
hole_pitch      = {M['pitch']};
hole_dia        = {M['hole_d']};
plate_hole_dia  = {M['plate_hole_d']};   // M3 close clearance, > screw_dia
screw_dia       = {M['screw_dia']};     // M3

// Standoff length is COMPUTED (design.required_standoff), not taken from the kit.
// The kit's 30 mm is 0.3 mm SHORT of the stack before any headroom - buy {STO['buy']} mm.
standoff_len    = {STO['buy']};
standoff_need   = {STO['need']:.1f};   // incl. {STO['headroom']:.1f} mm headroom
standoff_slack  = {STO['slack']:.1f};
cam_mod_t       = {C['mod_t']};
cam_mod_w       = {C['mod_w']};
pi_l            = {PI['L']};
pi_w            = {PI['W']};
pi_t            = {PI['t']};
"""
# --check exists because cad/frame.scad WAS STALE and nothing noticed. The model kept
# drawing inner_h 35.0 and arm_t 6.0 for the whole pass in which design.FRAME was
# corrected to 25.0 and 5.0, so cad/drone.scad cheerfully echoed "clearance above FC to
# top plate mm = 12.7" against a real figure of 3.2. A generated file that nobody
# regenerates is just a stale copy with a comment claiming otherwise, so preflight now
# gates it.
if "--check" in sys.argv:
    current = open(OUT).read() if os.path.exists(OUT) else ""
    if current == body:
        print("cad/frame.scad is current")
        sys.exit(0)
    print("FAIL: cad/frame.scad is stale - run tools/gen_scad_frame.py")
    sys.exit(1)

open(OUT, "w").write(body)
print(f"wrote {OUT}")
for k, v in (("wheelbase", F['wb']), ("arm_t", F['arm_t']),
             ("bottom_plate_t", F['bottom_t']), ("inner_h", F['inner_h'])):
    print(f"   {k:16s} {v}")
