#!/usr/bin/env python3
#MatekH743's hwdef against this board's -> docs/PINMAP.md
import json, os, sys
sys.path.insert(0, os.path.dirname(__file__))
from hwdef_pinmap import parse, sort_key

MATEK = "firmware/reference/MatekH743-hwdef.dat"
OURS = "firmware/NAVCORE_SoOP/hwdef.dat"
matek, _ = parse(MATEK)
ours, alts = parse(OURS)
d = json.load(open("tools/navcore_deltas.json"))


def note(p):
    for k, v in d["board_notes"].items():
        if p in k.split("/"):
            return v
    return ""


rows, differ = [], []
for p in sorted(set(matek) | set(ours), key=sort_key):
    a = matek[p]["label"] if p in matek else "-"
    b = ours[p]["label"] if p in ours else "-"
    e = ours.get(p) or matek[p]
    rows.append((p, a, b, e["periph"] if p in ours else "", " ".join(e["opts"]) if p in ours else "", note(p)))
    if a != b:
        differ.append((p, a, b, note(p)))
missing = [p for p, a, b, n in differ if not n]
if missing:
    sys.exit(f"no reason in tools/navcore_deltas.json for: {', '.join(missing)}")

out = ["# NAVCORE-SoOP - pin map",
       "",
       "**Generated by `tools/gen_pinmap.py` - do not hand-edit.**",
       f"Sources: `{MATEK}`, `{OURS}` (from `tools/gen_hwdef.py`) and `tools/navcore_deltas.json`.",
       "",
       f"{len(set(matek) & set(ours)) - sum(1 for _, a, b, _n in differ if a != '-' and b != '-')} pins "
       f"carry MatekH743's signal; {len(differ)} differ. Stock MatekH743 binaries boot on the board "
       "and drive the motors, USB, the SD card, the GPS port and the first IMU.",
       "",
       "## The pins that differ",
       "",
       "| Pin | MatekH743 | NAVCORE-SoOP | Why |",
       "|---|---|---|---|"]
out += [f"| `{p}` | {a} | **{b}** | {n} |" for p, a, b, n in differ]
out += ["", "## Every pin", "",
        "| Pin | MatekH743 | NAVCORE-SoOP | Periph | Options | Note |",
        "|---|---|---|---|---|---|"]
for p, a, b, per, o, n in rows:
    out.append(f"| `{p}` | {a} | {f'**{b}**' if a != b else b} | {per} | {o} | {n} |")
out += ["", "## MatekH743 features deliberately not populated", ""]
out += [f"- {x}" for x in d["unpopulated_matek_features"]]
out += ["", "## ADC design note", "", d["adc_design_note"], ""]

open("docs/PINMAP.md", "w").write("\n".join(out))
print(f"docs/PINMAP.md written: {len(rows)} pins, {len(differ)} differ from MatekH743")
