#!/usr/bin/env python3
#generate cad/plugs.scad - the analytical *plugged-in* assembly (Stage 5)
import math
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import pcbnew
import design

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "cad", "plugs.scad")
BOARD = os.path.join(ROOT, "NAVCORE-SoOP.kicad_pcb")

#how far a mated plug body stands off the board
PLUG_H = 6.0


B = design.BOARD
#model origin = the mounting-pattern centre (design.BOARD["CENTRE"])
CX, CY = B.get("CENTRE", (B["X0"] + B["W"] / 2, B["Y0"] + B["H"] / 2))


#Footprint-local mm -> board mm
def local_to_board(fp, lx, ly):
    p = fp.GetPosition()
    px, py = p.x / 1e6, p.y / 1e6
    if fp.IsFlipped():
        ly = -ly
    a = math.radians(-fp.GetOrientationDegrees())
    return (px + lx * math.cos(a) - ly * math.sin(a),
            py + lx * math.sin(a) + ly * math.cos(a))


#(dx, dy, ux, uy, width, depth, flipped) in the drone model's coordinates
def plug_of(board, ref):
    fp = board.FindFootprintByReference(ref)
    if fp is None:
        raise SystemExit(f"{ref}: not on the board")
    declared = design.MATING_FACE[ref]
    depth = design.MATING_CLEARANCE.get(ref, 6.0)

    poly = fp.GetCourtyard(pcbnew.B_CrtYd if fp.IsFlipped() else pcbnew.F_CrtYd)
    if not poly.OutlineCount():
        raise SystemExit(f"{ref}: no courtyard, cannot size the plug")
    bb = poly.BBox()
    cl, cr = bb.GetLeft() / 1e6, bb.GetRight() / 1e6
    ct, cb = bb.GetTop() / 1e6, bb.GetBottom() / 1e6
    cx, cy = (cl + cr) / 2, (ct + cb) / 2

    ox, oy = local_to_board(fp, *declared)
    px, py = fp.GetPosition().x / 1e6, fp.GetPosition().y / 1e6
    vx, vy = ox - px, oy - py
    n = math.hypot(vx, vy) or 1.0
    vx, vy = vx / n, vy / n
    #from the courtyard centre out to its face along the mating direction
    half = (abs(vx) * (cr - cl) + abs(vy) * (cb - ct)) / 2
    mx, my = cx + vx * half, cy + vy * half
    #width from the SIGNAL pads, projected across the mating direction
    if ref not in design.MATING_PLUG:
        raise SystemExit(f"{ref}: design.MATING_PLUG has no plug width for it")
    width = design.MATING_PLUG[ref][0]
    #board -> model: +x right, +y aft
    return (mx - CX, CY - my, vx, -vy, width, depth, fp.IsFlipped())


#the exact text cad/plugs.scad must hold
def generate(board=None):
    board = board or pcbnew.LoadBoard(BOARD)
    lines = [
        "// GENERATED by tools/gen_scad_plugs.py - DO NOT EDIT.",
        "// The plugged-in assembly (Stage 5): each edge connector's mated plug envelope,",
        "// sized from the footprint's courtyard mouth x design.MATING_CLEARANCE and",
        "// pointing along design.MATING_FACE. Regenerate rather than edit.",
        "//",
        "// INCLUDE this file from drone.scad after fc_z is defined: the plug z needs the",
        "// board's own stack position, which drone.scad owns.",
        "",
        "plug_h = %.1f;   // [A] how far a mated plug stands off the board" % PLUG_H,
        "",
        "// One mated plug: a box from the connector's mouth, outward along (ux, uy).",
        "module plug_box(x, y, ux, uy, w, depth, z0, h) {",
        "    translate([x, y, z0])",
        "        rotate([0, 0, atan2(uy, ux)])",
        "            translate([0, -w / 2, 0]) cube([depth, w, h]);",
        "}",
        "",
    ]
    names = []
    for ref in sorted(design.MATING_FACE, key=lambda r: (len(r), r)):
        dx, dy, ux, uy, w, d, flip = plug_of(board, ref)
        z0 = "fc_z - plug_h" if flip else "fc_z + fc_pcb"
        names.append(f"plug_{ref}")
        lines += [
            f"module plug_{ref}() {{   // {design.MATING_CLEARANCE.get(ref, 6.0):.1f} mm "
            f"clearance, {w:.2f} mm mouth",
            f"    plug_box({dx:.2f}, {dy:.2f}, {ux:.4f}, {uy:.4f}, {w:.2f}, {d:.2f}, "
            f"{z0}, plug_h);",
            "}",
        ]
    lines += ["", "module plugs() {"]
    lines += [f"    {n}();" for n in names]
    lines += ["}", ""]
    return "\n".join(lines)


def main():
    board = pcbnew.LoadBoard(BOARD)
    body = generate(board)

    if "--check" in sys.argv:
        current = open(OUT).read() if os.path.exists(OUT) else ""
        if current == body:
            print("cad/plugs.scad is current")
            return 0
        print("FAIL: cad/plugs.scad is stale - run tools/gen_scad_plugs.py")
        return 1

    open(OUT, "w").write(body)
    print(f"wrote {OUT}")
    for ref in sorted(design.MATING_FACE, key=lambda r: (len(r), r)):
        dx, dy, ux, uy, w, d, flip = plug_of(board, ref)
        print(f"   {ref:4s} {'bottom' if flip else 'top':6s} mouth ({dx:6.2f},{dy:6.2f}) "
              f"out ({ux:+.2f},{uy:+.2f})  {w:4.2f} x {d:.1f} mm")
    return 0


if __name__ == "__main__":
    sys.exit(main())
