#!/usr/bin/env python3
"""
Turn the DRC report's unconnected items into a prioritised hand-routing worklist.

The report lists them in no useful order and describes each endpoint twice. This
groups them by net, orders them the way the layout plan says to route them - the nets
where geometry affects function first - and gives each a location so you can jump
straight to it in KiCad.

Usage:  python3 tools/gen_worklist.py [board.kicad_pcb]
"""
import os, sys, re, subprocess
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import pcbnew, route

BOARD = sys.argv[1] if len(sys.argv) > 1 else "NAVCORE-SoOP.kicad_pcb"
OUT   = "docs/ROUTING-TODO.md"

# Phase E order from the plan: route the nets where layout affects function first.
PRIORITY = [
    ("crystal",        ("OSC_IN", "OSC_OUT")),
    ("buck switch",    ("BUCK_PH", "BUCK9_PH", "BUCK_COMP", "BUCK9_COMP")),
    ("MCU core power", ("VCAP1", "VCAP2", "VDDA", "VREF")),
    ("IMU SPI",        ("SPI1_", "SPI4_", "IMU1_CS", "IMU2_CS")),
    ("microSD",        ("SD_",)),
    ("USB",            ("USB_", "VBUS", "CC1", "CC2")),
    ("DShot motors",   ("M1", "M2", "M3", "M4")),
    ("analogue SoOP",  ("SOOP_",)),
    ("I2C",            ("I2C1_", "I2C2_")),
    ("UART / RC / CAN",("UART", "USART", "RC_IN", "CAN")),
    ("flash / flow",   ("SPI3_", "EXT_CS")),
    ("power rails",    ("+3V3", "+5V", "+9V", "VBAT", "GND")),
]


def bucket(net):
    for i, (name, pats) in enumerate(PRIORITY):
        for p in pats:
            if net == p or net.startswith(p):
                return i, name
    return len(PRIORITY), "other"


def main():
    os.makedirs("/tmp/nav", exist_ok=True)
    subprocess.run(["kicad-cli", "pcb", "drc", "--output", "/tmp/nav/wl.rpt",
                    "--severity-error", BOARD], capture_output=True, timeout=900)
    txt = open("/tmp/nav/wl.rpt").read()

    items = []
    for blk in re.split(r'^\[unconnected_items\][^\n]*\n', txt, flags=re.M)[1:]:
        eps = re.findall(r'@\(([\d.]+) mm, ([\d.]+) mm\): (Pad \S+|Zone|Track|Via)'
                         r'[^\[]*\[([^\]]+)\](?: of (\w+))?', blk[:400])[:2]
        if len(eps) != 2:
            continue
        net = eps[0][3]
        def name(e):
            kind = e[2].split()[0]
            if kind == "Pad":
                return f"{e[4]}.{e[2].split()[1]}"
            return kind.lower()
        items.append((bucket(net), net, name(eps[0]), name(eps[1]),
                      float(eps[0][0]), float(eps[0][1])))
    items.sort(key=lambda t: (t[0][0], t[1]))

    lines = ["# Hand-routing worklist", "",
             f"{len(items)} connections left, generated by `tools/gen_worklist.py` "
             f"from the DRC report on `{os.path.basename(BOARD)}`.", "",
             "Ordered the way `docs/LAYOUT.md` says to route them: the nets where",
             "geometry affects function come first, bulk power last. **In1.Cu and "
             "In2.Cu are planes - do not route on them.** Use F.Cu and B.Cu, and drop",
             "a via to the plane rather than running a rail across a signal layer.", ""]
    cur = None
    for (bi, bname), net, a, bb, x, y in items:
        if bname != cur:
            cur = bname
            n = sum(1 for it in items if it[0][1] == bname)
            lines += ["", f"## {bname} ({n})", "",
                      "| net | from | to | near |", "|---|---|---|---|"]
        lines.append(f"| `{net}` | {a} | {bb} | ({x:.1f}, {y:.1f}) |")
    open(OUT, "w").write("\n".join(lines) + "\n")
    print(f"wrote {OUT}: {len(items)} connections")
    for i, (name, _) in enumerate(PRIORITY):
        n = sum(1 for it in items if it[0][1] == name)
        if n:
            print(f"   {name:18} {n}")
    n = sum(1 for it in items if it[0][1] == "other")
    if n:
        print(f"   {'other':18} {n}")


if __name__ == "__main__":
    main()
