#!/usr/bin/env python3
#generate cad/mounts.scad from design.py: every part off the board, on a printed mount
#Usage: python3 tools/gen_scad_mounts.py [--check] [--stl]
#--check  fail if cad/mounts.scad is stale
#--stl    also export each printed part to cad/print/, laid out for printing
import os
import subprocess
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import design

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "cad", "mounts.scad")
PRINT_DIR = os.path.join(ROOT, "cad", "print")

F, TPM, B = design.FRAME, design.TOP_PLATE_MOUNT, design.BATT
MP, MT, INS, W = design.MOUNTED, design.MOUNTS, design.INSERTS, design.INSERT_WALL
LD = design.OFFBOARD["lidar"]
LH = design.MOUNTED["lidar"]

TOP_Z = F["bottom_t"] + TPM["rear_standoff"] + F["upper_t"]       #top plate's upper face
MID_Z = F["bottom_t"] + F["arm_t"]                                #mid plate's underside
CLEAR = {"M2": 2.4, "M2.5": 2.9, "M3": 3.4}                       #clearance holes
HEAD = {"M2": 4.2, "M2.5": 5.0, "M3": 6.0}                        #counterbores for heads


def boss_d(size):
    return INS[size]["od"] + 2 * W


def bore_depth(size):
    return INS[size]["L"] + 1.0


#every number the SCAD uses, derived once
def geometry():
    g = {}
    t = MT["antenna_tower"]
    foot, col, deck, gp = t["foot"], t["column"], t["deck"], t["gps"]
    patch, gps, saw = MP["iridium_patch"], MP["gps"], MP["sawbird"]
    patch_top = deck["z"] + deck["t"] + patch["H"]
    gps_top = patch_top + gp["top_above_patch"]
    gps_bot = gps_top - gps["H"]
    g["tower"] = dict(
        foot_z=TOP_Z, foot_t=foot["t"], foot_x=foot["x"], foot_y=foot["y"], y_post=foot["y0"],
        col_x=col["x"], col_y=col["y"], wall=col["wall"],
        deck_z=deck["z"], deck_t=deck["t"], deck_x=deck["x"], deck_y=deck["y"],
        patch_y=deck["y0"], patch_top=patch_top,
        gps_y=gp["y0"], gps_bot=gps_bot, gps_top=gps_top,
        pod_top=gps_bot + gp["pocket"],
        pod_h=gps_bot + gp["pocket"] - deck["z"] - deck["t"],
        pod_x=gps["L"] + 0.6 + 2 * (W + boss_d("M2")),
        pod_y=gp["pod_y"],
        lid_t=gp["lid_t"], proud=gps["H"] - gp["pocket"], lid_cbore=gp["lid_cbore"],
        lid_under_head=gps["H"] - gp["pocket"] + gp["lid_t"] - gp["lid_cbore"],
        saw_face=foot["y0"] + col["y"] / 2, saw_off=t["sawbird"]["standoff"],
        saw_z=t["sawbird"]["z0"])
    g["tower"]["post_x"] = [p[0] for p in TPM["rear_posts"][2:]]
    n = MT["nose_mount"]
    xi, rx = MP["xiao"], MP["rx"]
    cw = n["cradle"]["wall"]
    g["nose"] = dict(
        z=MID_Z, t=n["plate"]["t"], x=n["plate"]["x"], y0=n["plate"]["y0"],
        y1=n["plate"]["y1"],
        posts=[list(p) for p in TPM["front_posts"][2:]],
        cam_y=n["cradle"]["y0"], cam_x=xi["L"], cam_d=xi["W"], cam_h=xi["H"], cw=cw,
        cam_lid=n["cradle"]["lid_t"],
        rx_y=n["rx_pocket"]["y0"], rx_x=rx["W"], rx_l=rx["L"], rx_h=rx["H"],
        rx_wall=n["rx_pocket"]["wall"], rx_cover=n["rx_pocket"]["cover_t"],
        av=[n["antenna_v"]["x"], n["antenna_v"]["y"]],
        ah=[n["antenna_h"]["x"], n["antenna_h"]["y"], n["antenna_h"]["z"]],
        ant_l=MP["elrs_antenna"]["L"], ant_d=MP["elrs_antenna"]["dia"])
    lb = MT["lidar_bracket"]
    g["lidar"] = dict(t=lb["plate"]["t"], x=lb["plate"]["x"], y0=lb["plate"]["y0"],
                      y1=lb["plate"]["y1"], cbore=lb["plate"]["cbore"], y=lb["lidar_y0"],
                      posts=[list(p) for p in TPM["rear_posts"][:2]],
                      m2=[list(j[:2]) for j in lb["joints"][1]["at"]],
                      diag=LH["hole_diag_mm"])
    rc = MT["range_cradle"]
    rd = MP["range_down"]
    g["range"] = dict(y=rc["y0"], x=rc["x"], yl=rc["y"], top_t=rc["top_t"], lid_t=rc["lid_t"],
                      body_h=rc["top_t"] + rd["H"] + 0.3, holes=[list(j[:2]) for j in
                                                                   rc["joints"][0]["at"]])
    return g


G = geometry()


def ins(size):
    return f"[{INS[size]['bore']}, {bore_depth(size)}, {boss_d(size):.1f}]"


def scad():
    T, N, L, R = G["tower"], G["nose"], G["lidar"], G["range"]
    patch, gps, saw = MP["iridium_patch"], MP["gps"], MP["sawbird"]
    xi, rd = MP["xiao"], MP["range_down"]
    return f"""// GENERATED by tools/gen_scad_mounts.py - DO NOT EDIT.
// Every value comes from tools/design.py (MOUNTS, MOUNTED, INSERTS). Edit it there and
// regenerate, or the model, the CAD fit check and tools/fasteners.py drift apart.
//
// Axes as drone.scad: x to starboard, y AFT (the nose is -y), z up from the bottom plate's
// underside, (0, 0) the stack centre. Each mount is drawn where it sits on the aircraft;
// print_*() lays it on the bed.
//
// Heat-set inserts are bores [diameter, depth, boss diameter]: {design.INSERT_SRC}

ins_m2  = {ins("M2")};
ins_m25 = {ins("M2.5")};
ins_m3  = {ins("M3")};
ins_m3s = {ins("M3s")};

module bore(i, up = true) {{        // an insert bore, from the face it is pressed into
    translate([0, 0, up ? -i[1] : 0]) cylinder(d = i[0], h = i[1] + 0.01, $fn = 24);
}}
module hole(d, h) {{ translate([0, 0, -0.5]) cylinder(d = d, h = h + 1, $fn = 24); }}
module box(x0, x1, y0, y1, z0, z1) {{ translate([x0, y0, z0]) cube([x1 - x0, y1 - y0, z1 - z0]); }}

// ---- antenna tower: Iridium patch deck, GPS pod, SAWbird+ on the column --------------
// Bolts through the top plate's two rear posts, the only top-plate holes the battery
// leaves free, into the kit's 30 mm standoffs.
tower_foot_z  = {T['foot_z']};
tower_post_y  = {T['y_post']};
deck_z        = {T['deck_z']};        // clears the battery top by 8 mm
deck_top_z    = {T['deck_z'] + T['deck_t']};
patch_y       = {T['patch_y']};
patch_top_z   = {T['patch_top']};
gps_y         = {T['gps_y']};
gps_z         = {T['gps_bot']:.2f};      // module underside; its top is {T['gps_top']:.2f}
pod_top_z     = {T['pod_top']:.2f};
gps_lid_t     = {T['lid_t']};
gps_screw_x   = {T['pod_x'] / 2 - boss_d('M2') / 2:.2f};
sawbird_y     = {T['saw_face'] + T['saw_off']:.2f};      // back of the SAWbird's PCB
sawbird_z     = {T['saw_z']};
module antenna_tower() {{
    fx = {T['foot_x'] / 2}; fy = {T['foot_y'] / 2}; cx = {T['col_x'] / 2}; cy = {T['col_y'] / 2};
    w = {T['wall']}; dz = deck_z; dt = {T['deck_t']};
    px = {T['pod_x'] / 2}; py = {T['pod_y'] / 2};
    color("#d9822b") difference() {{
        union() {{
            box(-fx, fx, tower_post_y - fy, tower_post_y + fy, tower_foot_z, tower_foot_z + {T['foot_t']});
            box(-cx, cx, tower_post_y - cy, tower_post_y + cy, tower_foot_z, dz);
            box(-{T['deck_x'] / 2}, {T['deck_x'] / 2}, patch_y - {T['deck_y'] / 2}, patch_y + {T['deck_y'] / 2}, dz, deck_top_z);
            box(-px, px, patch_y + {T['deck_y'] / 2} - 1, gps_y + py, dz, deck_top_z);    // the GPS tongue
            // bosses under the deck for the patch's and the GPS pod's inserts, outboard of
            // the battery
            for (h = {[list(h) for h in patch['holes']]})
                translate([h[0], patch_y + h[1], deck_top_z - ins_m3[1] - 1]) cylinder(d = ins_m3[2], h = ins_m3[1] + 1);
            for (s = [-1, 1]) translate([s * gps_screw_x, gps_y, deck_top_z - ins_m2[1] - 1]) cylinder(d = ins_m2[2], h = ins_m2[1] + 1);
            // bosses on the column's aft face for the SAWbird+
            for (h = {[list(h) for h in saw['holes']]})
                translate([h[0], {T['saw_face']}, sawbird_z + h[1]]) rotate([-90, 0, 0])
                    cylinder(d = ins_m3s[2], h = {T['saw_off']});
        }}
        for (x = {T['post_x']}) translate([x, tower_post_y, tower_foot_z]) hole({CLEAR['M3']}, {T['foot_t']});
        // the column is a duct: coax and the GPS lead run down it and out of the slot
        box(-cx + w, cx - w, tower_post_y - cy + w, tower_post_y + cy - w, tower_foot_z - 1, deck_top_z + 1);
        box(-5, 5, tower_post_y - cy - 1, tower_post_y, tower_foot_z + {T['foot_t']}, tower_foot_z + {T['foot_t']} + 8);
        for (h = {[list(h) for h in patch['holes']]}) translate([h[0], patch_y + h[1], deck_top_z]) bore(ins_m3);
        for (s = [-1, 1]) translate([s * gps_screw_x, gps_y, deck_top_z]) bore(ins_m2);
        for (h = {[list(h) for h in saw['holes']]})
            translate([h[0], sawbird_y, sawbird_z + h[1]]) rotate([-90, 0, 0]) bore(ins_m3s);
    }}
}}
module gps_pod() {{
    px = {T['pod_x'] / 2}; py = {T['pod_y'] / 2}; g = {(gps['L'] + 0.6) / 2};
    color("#e0a050") translate([0, gps_y, deck_top_z]) difference() {{
        box(-px, px, -py, py, 0, pod_top_z - deck_top_z);
        box(-g, g, -g, g, gps_z - deck_top_z, pod_top_z - deck_top_z + 1);
        box(-4, 4, -py - 1, 0, gps_z - deck_top_z, pod_top_z - deck_top_z + 1);   // the lead, toward the column
        for (s = [-1, 1]) translate([s * gps_screw_x, 0, 0]) hole({CLEAR['M2']}, pod_top_z - deck_top_z);
    }}
}}
module gps_lid() {{
    px = {T['pod_x'] / 2}; py = {T['pod_y'] / 2}; g = {(gps['L'] + 0.6) / 2};
    color("#e0a050") translate([0, gps_y, pod_top_z]) difference() {{
        box(-px, px, -py, py, 0, {T['proud']} + gps_lid_t);
        box(-g, g, -g, g, -1, {T['proud']});                  // over the module's shoulders
        box(-8, 8, -8, 8, 0, {T['proud']} + gps_lid_t + 1);   // the ceramic patch sees sky
        for (s = [-1, 1]) translate([s * gps_screw_x, 0, 0]) {{
            hole({CLEAR['M2']}, {T['proud']} + gps_lid_t);
            translate([0, 0, {T['proud']} + gps_lid_t - {T['lid_cbore']}]) cylinder(d = {HEAD['M2']}, h = {T['lid_cbore']} + 1, $fn = 24);
        }}
    }}
}}
module gps() {{
    translate([0, gps_y, gps_z]) {{
        color("#3050a0") box({-gps['L'] / 2}, {gps['L'] / 2}, {-gps['W'] / 2}, {gps['W'] / 2}, 0, {gps['H'] - 4});
        color("#c8b070") box(-7.5, 7.5, -7.5, 7.5, {gps['H'] - 4}, {gps['H']});
    }}
}}
module iridium_patch() {{
    translate([0, patch_y, deck_z + {T['deck_t']}]) difference() {{
        union() {{
            color("#b0b4b8") box({-patch['W'] / 2}, {patch['W'] / 2}, {-patch['L'] / 2}, {patch['L'] / 2}, 0, {patch['flange_t']});
            color("#e8e4d8") box({-patch['W'] / 2 + 8}, {patch['W'] / 2 - 8}, {-patch['L'] / 2 + 8}, {patch['L'] / 2 - 8}, 0, {patch['H']});
        }}
        for (h = {[list(h) for h in patch['holes']]}) translate([h[0], h[1], 0]) hole(3.2, {patch['flange_t']});
    }}
}}
module sawbird() {{
    translate([0, sawbird_y, sawbird_z]) color("#1f5f3f")
        box({-saw['W'] / 2}, {saw['W'] / 2}, 0, {saw['H']}, {-saw['L'] / 2}, {saw['L'] / 2});
}}

// ---- nose mount: XIAO camera, RP3 receiver, both ELRS antennas ---------------------------
// Clamped under the mid plate by the two forward front-post screws, in the gap the arms
// leave there. Everything hangs below the plate. Ahead of the carbon, and the length of
// the aircraft from the Iridium patch.
nose_z   = {N['z']};                 // the mid plate's underside
cam_y    = {N['cam_y']};
rx_y     = {N['rx_y']};
cam_x    = {N['cam_x'] / 2 + 0.3 + N['cw']};      // cradle half-width
cam_d    = {N['cam_d'] / 2 + 0.3 + N['cw']};      // cradle half-depth
cam_boss = cam_x + ins_m2[2] / 2 - 1;
cam_bot  = nose_z - {N['t']} - {N['cam_h']} - 0.3 - {N['cw']};     // 0.3 mm headroom
rx_w     = {N['rx_x'] / 2 + 0.2 + N['rx_wall']};
rx_l     = {N['rx_l'] / 2 + 0.2 + N['rx_wall']};
rx_bot   = nose_z - {N['t']} - {N['rx_h'] + 0.4};
rx_boss  = rx_w + ins_m2[2] / 2 - 1;
module nose_mount() {{
    t = {N['t']}; hx = {N['x'] / 2}; pz = nose_z - t; cw = {N['cw']};
    color("#d9822b") difference() {{
        union() {{
            box(-hx, hx, {N['y1']}, {N['y0']}, pz, nose_z);
            // camera cradle, the XIAO slides in from below; with its lid's bosses
            box(-cam_x, cam_x, cam_y - cam_d, cam_y + cam_d, cam_bot, pz);
            for (s = [-1, 1]) translate([s * cam_boss, cam_y, cam_bot]) cylinder(d = ins_m2[2], h = pz - cam_bot);
            // receiver pocket, with its cover's bosses
            box(-rx_w, rx_w, rx_y - rx_l, rx_y + rx_l, rx_bot, pz);
            for (s = [-1, 1]) translate([s * rx_boss, rx_y, rx_bot]) cylinder(d = ins_m2[2], h = pz - rx_bot);
            // antenna holders: one vertical (up through the plate), one pointing forward
            translate([{N['av'][0]}, {N['av'][1]}, pz - 12]) cylinder(d = 8, h = 12);
            box({N['ah'][0] - 5}, {N['ah'][0] + 5}, {N['ah'][1]}, {N['ah'][1] + 5}, {N['ah'][2] - 4}, pz);
        }}
        for (p = {N['posts']}) translate([p[0], p[1], pz]) hole({CLEAR['M3']}, t);
        box(-cam_x + cw, cam_x - cw, cam_y - cam_d + cw, cam_y + cam_d - cw, cam_bot - 1, pz - 0.01);
        translate([0, cam_y - cam_d - 1, cam_bot + cw + {N['cam_h']} - 7]) rotate([-90, 0, 0]) cylinder(d = 10, h = cw + 2);
        for (s = [-1, 1]) translate([s * cam_boss, cam_y, cam_bot]) bore(ins_m2, false);
        box(-rx_w + {N['rx_wall']}, rx_w - {N['rx_wall']}, rx_y - rx_l + {N['rx_wall']}, rx_y + rx_l - {N['rx_wall']}, rx_bot - 1, pz - 0.01);
        box(-3, 3, rx_y + rx_l - {N['rx_wall']} - 0.01, rx_y + rx_l + 0.01, rx_bot + 1, pz - 0.01);   // wires out
        for (s = [-1, 1]) translate([s * rx_boss, rx_y, rx_bot]) bore(ins_m2, false);
        translate([{N['av'][0]}, {N['av'][1]}, pz - 12]) hole(3.4, 12 + t);
        translate([{N['ah'][0]}, {N['ah'][1]} - 0.5, {N['ah'][2]}]) rotate([-90, 0, 0]) cylinder(d = 3.4, h = 6, $fn = 24);
    }}
}}
module xiao_lid() {{
    color("#e0a050") translate([0, cam_y, cam_bot - {N['cam_lid']}]) difference() {{
        box(-cam_boss - ins_m2[2] / 2, cam_boss + ins_m2[2] / 2, -cam_d, cam_d, 0, {N['cam_lid']});
        for (s = [-1, 1]) translate([s * cam_boss, 0, 0]) hole({CLEAR['M2']}, {N['cam_lid']});
    }}
}}
module rx_cover() {{
    color("#e0a050") translate([0, rx_y, rx_bot - {N['rx_cover']}]) difference() {{
        box(-rx_boss - ins_m2[2] / 2, rx_boss + ins_m2[2] / 2, -rx_l, rx_l, 0, {N['rx_cover']});
        for (s = [-1, 1]) translate([s * rx_boss, 0, 0]) hole({CLEAR['M2']}, {N['rx_cover']});
    }}
}}
module rec_cam() {{                  // XIAO ESP32S3 Sense, standing in its cradle, lens forward
    translate([0, cam_y, cam_bot + {N['cw']}]) {{
        color("#23272e") box({-xi['L'] / 2}, {xi['L'] / 2}, {-xi['W'] / 2}, {xi['W'] / 2}, 0, {xi['H']});
        color("#0d0f11") translate([0, {-xi['W'] / 2}, {xi['H'] - 7}]) rotate([90, 0, 0]) cylinder(d = {xi['lens_dia']}, h = 3);
    }}
}}
module rx() {{
    translate([0, rx_y, rx_bot + 0.2]) color("#202020")
        box({-N['rx_x'] / 2}, {N['rx_x'] / 2}, {-N['rx_l'] / 2}, {N['rx_l'] / 2}, 0, {N['rx_h']});
}}
module elrs_antennas() {{
    color("#101010") {{
        translate([{N['av'][0]}, {N['av'][1]}, nose_z - {N['t']} - 10]) cylinder(d = {N['ant_d']}, h = {N['ant_l']}, $fn = 16);
        translate([{N['ah'][0]}, {N['ah'][1]} + 4, {N['ah'][2]}]) rotate([90, 0, 0]) cylinder(d = {N['ant_d']}, h = {N['ant_l']}, $fn = 16);
    }}
}}

// ---- lidar bracket: the LD06, upside down under the bottom plate ------------------------
// Hangs from the two forward rear-post screws (into the 30 mm standoffs) and the front
// pair of the 20x20 M2 holes; the heads sit in counterbores because the lidar covers them.
lidar_bracket_t = {L['t']};
lidar_y         = {L['y']};
module lidar_bracket() {{
    t = {L['t']}; cb = {L['cbore']};
    color("#d9822b") difference() {{
        box({-L['x'] / 2}, {L['x'] / 2}, {L['y0']}, {L['y1']}, -t, 0);
        for (p = {L['posts']}) translate([p[0], p[1], -t]) {{ hole({CLEAR['M3']}, t); translate([0, 0, -1]) cylinder(d = {HEAD['M3']}, h = cb + 1, $fn = 24); }}
        for (p = {L['m2']}) translate([p[0], p[1], -t]) {{ hole({CLEAR['M2']}, t); translate([0, 0, -1]) cylinder(d = {HEAD['M2']}, h = cb + 1, $fn = 24); }}
        // the LD06's two diagonal M2.5 holes, screwed from the lidar's side
        for (s = [-1, 1]) translate([s * {L['diag'][0] / 2}, lidar_y - s * {L['diag'][1] / 2}, -t]) bore(ins_m25, false);
    }}
}}
module lidar360() {{
    translate([0, lidar_y, -lidar_bracket_t - {LD['H_mm']}]) color("#3b4048")
        linear_extrude({LD['H_mm']}) offset(r = 2) square([{LD['L_mm'] - 4}, {LD['W_mm'] - 4}], center = true);
}}

// ---- downward rangefinder cradle: the TFS20-L, under the bottom plate -------------------
// Two M2 through the lid, the cradle and the plate, nuts on top: the sensor has no holes,
// so the lid pins it in its pocket.
range_y      = {R['y']};
range_body_h = {R['body_h']:.2f};
module range_cradle() {{
    hx = {R['x'] / 2}; hy = {R['yl'] / 2}; px = {rd['L'] / 2 + 0.2}; py = {rd['W'] / 2 + 0.2};
    color("#d9822b") translate([0, range_y, -range_body_h]) difference() {{
        box(-hx, hx, -hy, hy, 0, range_body_h);
        box(-px, px, -py, py, -1, range_body_h - {R['top_t']});
        box(-2.5, 2.5, py - 0.01, hy + 0.01, 0, 3);             // the lead's exit
        for (h = {R['holes']}) translate([h[0], h[1] - range_y, 0]) hole({CLEAR['M2']}, range_body_h);
    }}
}}
module range_lid() {{
    hx = {R['x'] / 2}; hy = {R['yl'] / 2};
    color("#e0a050") translate([0, range_y, -range_body_h - {R['lid_t']}]) difference() {{
        box(-hx, hx, -hy, hy, 0, {R['lid_t']});
        box(-5, 5, -8, 8, -1, {R['lid_t']} + 1);                 // the optics' window
        for (h = {R['holes']}) translate([h[0], h[1] - range_y, 0]) hole({CLEAR['M2']}, {R['lid_t']});
    }}
}}
module belly_sensor() {{
    translate([0, range_y, -{R['top_t']} - {rd['H']}]) color("#2a2f36")
        box({-rd['L'] / 2}, {rd['L'] / 2}, {-rd['W'] / 2}, {rd['W'] / 2}, 0, {rd['H']});
}}

module mounts() {{
    antenna_tower(); gps_pod(); gps_lid(); nose_mount(); xiao_lid(); rx_cover(); lidar_bracket();
    range_cradle(); range_lid();
}}
module mounted_parts() {{
    gps(); iridium_patch(); sawbird(); rx(); elrs_antennas();
}}

// ---- laid out for printing: each part on the bed, in the orientation it prints ---------
module print_antenna_tower() {{ translate([0, 0, deck_top_z]) rotate([180, 0, 0]) antenna_tower(); }}
module print_gps_pod()       {{ translate([0, 0, -deck_top_z]) gps_pod(); }}
module print_gps_lid()       {{ translate([0, 0, pod_top_z + {T['proud'] + T['lid_t']}]) rotate([180, 0, 0]) gps_lid(); }}
module print_nose_mount()    {{ translate([0, 0, nose_z]) rotate([180, 0, 0]) nose_mount(); }}
module print_xiao_lid()      {{ translate([0, 0, -(cam_bot - {N['cam_lid']})]) xiao_lid(); }}
module print_rx_cover()      {{ translate([0, 0, -(rx_bot - {N['rx_cover']})]) rx_cover(); }}
module print_lidar_bracket() {{ translate([0, 0, lidar_bracket_t]) lidar_bracket(); }}
module print_range_cradle()  {{ rotate([180, 0, 0]) range_cradle(); }}
module print_range_lid()     {{ translate([0, 0, range_body_h + {R['lid_t']}]) range_lid(); }}
"""


PRINTED = ["antenna_tower", "gps_pod", "gps_lid", "nose_mount", "xiao_lid", "rx_cover", "lidar_bracket",
           "range_cradle", "range_lid"]


def export_stl():
    os.makedirs(PRINT_DIR, exist_ok=True)
    for name in PRINTED:
        out = os.path.join(PRINT_DIR, name + ".stl")
        src = os.path.join(PRINT_DIR, "." + name + ".scad")
        open(src, "w").write(f"use <{OUT}>\n$fn = 48;\nprint_{name}();\n")
        try:
            r = subprocess.run(["openscad", "-o", out, src], capture_output=True, text=True,
                               timeout=600)
        finally:
            os.unlink(src)
        if not os.path.exists(out):
            sys.exit(f"FAIL: {name} did not export\n{r.stderr[-1500:]}")
        print(f"  wrote cad/print/{name}.stl")


def main():
    body = scad()
    if "--check" in sys.argv:
        if (open(OUT).read() if os.path.exists(OUT) else "") == body:
            print("cad/mounts.scad is current")
            return 0
        print("FAIL: cad/mounts.scad is stale - run tools/gen_scad_mounts.py")
        return 1
    open(OUT, "w").write(body)
    print(f"wrote {OUT}")
    if "--stl" in sys.argv:
        export_stl()
    return 0


if __name__ == "__main__":
    sys.exit(main())
